global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param podAnnotations Annotations for BigiD pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  podAnnotations: {}
  bigid:
    collaboration:
      replicaCount: 1
      serviceAccount:
        create: true
        annotations: {}
      port: 4010
      image:
        repository: "bigid-collaboration"
        # this will allow us to pass in a different image tag than the main supplied, if empty will take from root values.yaml file
        # (i.e: main instead of staging, or a specific collaboration branch)
        #  for example: --set collaboration.global.bigid.collaboration.image.tag=main
        tag: ""
      securityContext:
        # capabilities:
        #   drop:
        #   - ALL
        #   - NET_RAW
        # # readOnlyRootFilesystem: true
        # allowPrivilegeEscalation: false
        # runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
      resources:
        requests:
          memory: "256Mi"
          cpu: "50m"
        limits:
          memory: "6Gi"
          cpu: "1"
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
