global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations: []
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  podAnnotations: {}
  bigid:
    ## @param global.bigid.containerSecurityContext Security Context for BigID containers
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
    ## @param global.bigid.podSecurityContext Security Context for BigID pods
    podSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsGroup: 1001
    saasEnv: "staging"
    web:
      showGuidedTourScanTemplatesFF: true
      showGuidedTourClassificationStepFF: true
      serviceAccount:
        create: true
        annotations: {}
      showGuidedTourSavedScansFF: true
      showDialogGuideConvertScanProfile: true
      showNewScanInsightFF: true
      nodeMaxOldSpaceSizePercent: 85
      auth0DBConnectionName: ""
      auth0CloudHostDomain: ""
      auth0CloudTestMode: ""
      domain: ""
      maxUsers: ""
      okta_app_id: ""
      apiToken: ""
      fmsdEnabled: false
      enabledCustomerIdp: true
      mtCorrelation:
        enabled: false
      ## bigid-web Audit-log persistence, you need to create StorageClass, see example https://kubernetes.io/docs/concepts/storage/storage-classes/#introduction
      ## https://kubernetes.io/docs/concepts/storage/persistent-volumes/
      auditLogPersistency: false
      printAuditToStdout: false
      useAuditObjectApi: false
      writeAuditLogsToMq: false
      enableNewUxNavigation: true
      enableNewCertificatesManagementView: true
      enableCatalogHistory: false
      pipeToOrch2Conditionally: true
      webPvcStorageClassName: standard
      webPvcStorageSizeGb: 1Gi
      licenseKey: ""
      legacyAdminRoles: false
      pipeScanPartsToOrch2FF: false
      showNavigationGuidedTour: true
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 5
        targetCPUUtilizationPercentage: 85
        scaleDownPolicy:
          stabilizationWindowSeconds: 900
          periodSeconds: 300
          value: 10
      auth0TenantLambdaClientId: ""
      Auth0TokenClaimsNamespace: "https://bigid.cloud/claims"
      Auth0AppNameAttrInTokenClaims: "appName"
      auth0RedirectProtocol: "https://"
      bigidUiPortExt: "443"
      idpType: ""
      isSmallId: false
      enableCloudMerger: false
      samlDenyLogin:
        enabled: false
      replicaCount: 1
      image:
        repository: "bigid-web"
      port: 3000
      logLevel: info
      nodeOptions: ""
      podSecurityContext:
        fsGroup: 1001
      podAnnotations: {}
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      ## Configure extra options for liveness probe
      livenessProbe:
        enabled: true
        path: /health
        port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      ## Configure extra options for readiness probe
      readinessProbe:
        enabled: true
        path: /health
        port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
        failureThreshold: 3
        successThreshold: 1
      extraEnvVars: []
      amplitude:
        enabled: false
        apiKey: ""
