{{- if .Values.global.bigid.catalogProcessor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigid-catalog-processor
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-catalog-processor
  {{- with .Values.global.bigid.catalogProcessor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
