global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param podAnnotations Annotations for BigiD pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  podAnnotations: {}
  bigid:
    saasEnv: "staging"
    dataCatalogConsumer:
      create: false
      replicaCount: 1
      serviceAccount:
        create: true
        annotations: {}
      port: 3554
      nodeOptions: ""
      logLevel: info
      nodeMaxOldSpaceSizePercent: 85
      terminationGracePeriodSeconds: 60
      appTerminationGracePeriodSeconds: "55"
      graceComplete:
        enabled: false
        countThreshold: 50
        pctThreshold: 0.99
      image:
        repository: "bigid-data-catalog"
      securityContext: {}
      prefetchCount: 40
      podAnnotations: {}
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      extraEnvVars: []
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 5
        averageValue: 250
        scaleDownPolicy:
          stabilizationWindowSeconds: 900
          periodSeconds: 300
          value: 10
