{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-discovery.fullname" . }}
  labels:
    {{- include "aws-discovery.labels" . | nindent 4 }}
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aws-discovery.selectorLabels" . | nindent 4 }}
{{- end }}
