apiVersion: v1
kind: Service
metadata:
  name: bigid-ui
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-ui
    {{- with .Values.global.bigid.ui.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.bigid.ui.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if or (eq .Values.global.ingress.class "alb") (eq .Values.global.bigid.ui.service.type "NodePort") }}
  type: NodePort
  {{- end }}
  ports:
   - port: {{ .Values.global.bigid.ui.service.port }}
     {{- if eq (.Values.global.bigid.ui.service.port | int ) 443 }}
     targetPort: 8443
     {{- else }}
     targetPort: 8080
     {{- end }}
     protocol: TCP
     name: http
     {{- if or (eq .Values.global.ingress.class "alb") ( eq .Values.global.bigid.ui.service.type "NodePort") }}
     nodePort: {{ .Values.global.bigid.ui.service.nodePort }}
     {{- end }}
  selector:
    app: bigid-ui
