{{- if (gt (len .Values.global.ingress.class) 0) }}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
apiVersion: networking.k8s.io/v1
{{ else }}
apiVersion: networking.k8s.io/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: bigid-ui-ingress
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    {{- if eq .Values.global.ingress.class "alb" }}
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "5"
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/target-type: instance
    {{- else if eq .Values.global.ingress.class "nginx" }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/rewrite-target: /
    {{- else if eq .Values.global.ingress.class "kong" }}
    {{- if .Capabilities.APIVersions.Has "configuration.konghq.com/v1" }}
    kong.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- else }}
    # Use older annotation for compatibility with Kong versions < 1.3
    konghq.com/override: "bigid-ui"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
    {{- end }}
    {{- end }}
  {{- with .Values.global.ingress.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default "" .Values.global.ingress.class | quote }}
  {{- if not (eq .Values.global.ingress.bigidHost "") }}
  tls:
    - hosts:
        - {{ .Values.global.ingress.bigidHost | quote }}
      secretName: tlssecret
  {{- end }}
  rules:
  {{- if not (eq .Values.global.ingress.bigidHost "") }}
  - host: {{ .Values.global.ingress.bigidHost | quote }}
    http:
  {{- else }}
  - http:
  {{- end }}
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bigid-ui
            port:
              number: {{ .Values.global.bigid.ui.service.port }}
{{- end }}
