{{- if .Values.global.bigid.snippetPersister.create -}}
{{- if .Values.global.bigid.snippetPersister.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigid-snippet-persister
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-snippet-persister
  {{- with .Values.global.bigid.snippetPersister.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
