{{- if .Values.global.bigid.lineage.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigid-lineage
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-lineage
  {{- with .Values.global.bigid.lineage.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
