{{- if .Values.global.bigid.scaler.create -}}
{{- if and (.Values.global.bigid.scanner.hadoop.create) (not .Values.global.bigid.scanner.remote.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigid-hadoop-scaler
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-hadoop-scaler
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{ include "global.skipCheckovAnnotations" . | nindent 4 }}
    {{- with .Values.global.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.global.bigid.scaler.replicaCount }}
  {{- if .Values.global.bigid.scaler.updateStrategy }}
  strategy: {{- toYaml .Values.global.bigid.scaler.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: bigid-hadoop-scaler
      {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.bigid.scaler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: bigid-hadoop-scaler
        {{- with .Values.global.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccount: bigid-scanner-scaler
      automountServiceAccountToken: false
      containers:
      - name: bigid-hadoop-scaler
        image: "{{ .Values.global.image.repository }}/{{ .Values.global.bigid.scaler.image.repository }}{{ template "bigid.scannerArmRepository" . }}:{{ .Values.global.image.tag }}"
        {{- if .Values.global.bigid.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.global.bigid.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
        envFrom:
        - secretRef:
            name: mongodb-base-configuration
        - configMapRef:
            name: global-configuration
        env:
          - name: "DL_REGION_NAME"
            value: "{{ .Values.global.bigid.scaler.dlRegionName }}"
          - name: "DATADOG_ENABLED"
            value: "{{ .Values.global.bigid.ddMetrics.dataDogEnabled }}"
          - name: "KINESIS_ENABLED"
            value: "{{ .Values.global.bigid.scaler.kinesisEnabled }}"
          - name: "TELEMETRY_ENABLED"
            value: "{{ .Values.global.bigid.scaler.telemetryEnabled }}"
          - name: "DL_STREAM_NAME"
            value: "{{ .Values.global.bigid.scaler.dlStreamName }}"
          - name: "DD-API-KEY"
            value: "{{ .Values.global.bigid.ddMetrics.ddApiKey }}"
          - name: DD-URI
            value: "{{ .Values.global.bigid.ddMetrics.ddURI }}"
          - name: "K8S_NAMESPACE"
            value: "{{ .Release.Namespace }}"
          - name: "K8S_DEPLOYMENT"
            value: "{{ .Values.global.bigid.scaler.scannerName }}"
          - name: BIGID_CACHE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bigid-auth-secret
                key: redis-pass
          - name: "BIGID_CACHE_DB"
            value: "5"
          - name: "SAAS_ENV"
            value: "{{ .Values.global.bigid.saasEnv }}"
          - name: "SCANNER_GROUP"
            value: "{{ .Values.global.bigid.scaler.scannerGroup }}"
          - name: "SPRING_PROFILES_ACTIVE"
            value: "k8s"
          - name: QUEUE_SCAN_PARTS_SIZE_SCALE_UP_THRESHOLD
            value: "{{ .Values.global.bigid.scaler.queueScanPartsThreshold }}"
          - name: "CPU_SCALE_UP_THRESHOLD"
            value: "{{ .Values.global.bigid.scaler.cpuThreshold }}"
          - name: "CPU_SCALE_DOWN_THRESHOLD"
            value: "{{ .Values.global.bigid.scaler.cpuScaleDownThreshold }}"
          - name: "QUEUE_SIZE_SCALE_UP_THRESHOLD"
            value: "{{ .Values.global.bigid.scaler.queueThreshold }}"
          - name: MULTI_TENANT_MODE_ENABLED
            value: "{{ .Values.global.bigid.multiTenantMode.enabled }}"
          {{- if .Values.global.bigid.scaler.scannerController.enabled }}
          - name: "SCANNER_DEPLOYMENT_YAML_PATH"
            value: "/hadoop.yaml"
          {{- end }}
          - name: "SCANNER_MIN_PODS"
            value: "{{ .Values.global.bigid.scaler.minPods }}"
          - name: "SCANNER_MAX_PODS"
            value: "{{ .Values.global.bigid.scaler.maxPods }}"
          - name: "SCANNER_THREADS_ACTIVITY_HISTOGRAM_LENGTH_MINUTES"
            value: "{{ .Values.global.bigid.scaler.threadsActivityHistogramLength }}"
          - name: "SCAN_PARTS_SIZE_QUEUE_HISTOGRAM_LENGTH_MINUTES"
            value: "{{ .Values.global.bigid.scaler.partsSizeQueueHistogramLength }}"
          - name: QUEUE_HISTOGRAM_LENGTH_MINUTES
            value: "{{ .Values.global.bigid.scaler.queueHistogramLength }}"
          - name: SCALE_IN_CANDIDATE_LOCK_TTL_MINUTES
            value: "{{ .Values.global.bigid.scaler.lockTTLMinutes }}"
          - name: SCALING_EVENT_COOL_DOWN_MINUTES
            value: "{{ .Values.global.bigid.scaler.scalingCoolDownMinutes }}"
          - name: SCALE_IN_CANDIDATE_GRACE_MINUTES
            value: "{{ .Values.global.bigid.scaler.candidateGraceMinutes }}"
          - name: K8S_DEPLOYMENT_LABEL
            value: "app={{ .Values.global.bigid.scaler.scannerName }}"
        resources:
          {{- toYaml .Values.global.bigid.scaler.resources | nindent 10 }}
      {{- if .Values.global.bigid.scaler.scannerController.enabled }}
        volumeMounts:
        - name: hadoop-yaml
          mountPath: /hadoop.yaml
          subPath: hadoop.yaml
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: hadoop.yaml
            path: hadoop.yaml
          name: hadoop-yaml
        name: hadoop-yaml
      {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- if .Values.global.bigid.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.global.bigid.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
