{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retention-web-gateway
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: data-retention-web-gateway
  annotations:
    {{ include "global.skipCheckovAnnotations" . | nindent 4 }}
    {{- with .Values.global.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      app: data-retention-web-gateway
  template:
    metadata:
      labels:
        app: data-retention-web-gateway
    spec:
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- if .Values.global.bigid.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.global.bigid.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: true
      containers:
        - name: data-retention-web-gateway
          image: "{{ .Values.image.registry }}/{{ .Values.gateway.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          securityContext: {{- omit .Values.global.bigid.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.gateway.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.gateway.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: {{ .Values.gateway.service.port }}
          envFrom:
          - secretRef:
              name: mongodb-base-configuration
          - configMapRef:
              name: mongodb-node-configuration
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.gateway.profile }}
            - name: BIG_ID_CORE_URL
              value: "http://bigid-web:3000"
            {{- if .Values.global.bigid.generateToken.enabled | default false }}
            - name: BIGID_SERVICE_USER_JWT
              valueFrom:
                secretKeyRef:
                  name: bigid-jwt-token
                  key: token
                  optional: true
            {{- else }}
            - name: BIGID_SERVICE_USER_JWT
              value: {{ .Values.gateway.serviceUserJWT }}
            {{- end }}
            - name: EVALUATION_DSAR_REPORT_WAITING_TIMEOUT
              value: {{ .Values.gateway.dsarTimeout | quote }}
            - name: BIGID_MONGO_SSL
              value: {{ .Values.mongodb.ssl | quote }}
            - name: MONGO_BY_EXTERNAL_FULL_URL
              value: {{ .Values.mongodb.byExternalFullUrl | quote }}
            - name: MONGO_EXTERNAL_FULL_URL
            {{- if .Values.mongodb.mongoFullUrl }}
              value: {{ .Values.mongodb.mongoFullUrl | quote }}
            {{- else }}
              value: 'mongodb://$(BIGID_MONGO_USER):$(BIGID_MONGO_PWD)@$(BIGID_MONGO_HOST_EXT):$(BIGID_MONGO_PORT)/{{ .Values.mongodb.mongoUri }}&ssl=$(BIGID_MONGO_SSL)&tlsAllowInvalidHostnames=$(BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION)'
            {{- end }}
            - name: WEB_GATEWAY_JVM_OPTS
              value: {{ .Values.gateway.jvmOpts | quote }}
          volumeMounts:
            - name: logs
              mountPath: /usr/local/dataretention/logs
            - name: mongo-ssl-truststore-secrets
              mountPath: /etc/ssl/bigid
              readOnly: true
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      volumes:
        - name: logs
          emptyDir: {}
        - name: mongo-ssl-truststore-secrets
          secret:
            secretName: mongo-ssl-truststore-secrets
            defaultMode: 420
      hostname: data-retention-web-gateway
      restartPolicy: Always
{{- end }}
