{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "classifier-helper.fullname" . }}"
  labels:
    {{- include "classifier-helper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "classifier-helper.selectorLabels" . | nindent 4 }}
{{- end }}
