{{- if ( hasKey .Values.global.bigid "generateToken") }}
{{- if .Values.global.bigid.generateToken.enabled | default false }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: token-sa
  annotations: {}
  namespace: {{ .Release.Namespace | quote }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: token-sa-role-binding
  namespace: {{ .Release.Namespace | quote }}
  annotations: {}
subjects:
- kind: ServiceAccount
  name: token-sa
  namespace: {{ .Release.Namespace | quote }}
roleRef:
 kind: Role
 name: token-sa-role
 apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-sa-role
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "create"]
{{- end }}
{{- end }}
