{{- if .Values.global.bigid.reportingEtl.create -}}
apiVersion: v1
kind: Service
metadata:
  name: bigid-reporting-etl
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-reporting-etl
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.global.bigid.reportingEtl.port }}
      targetPort: {{ .Values.global.bigid.reportingEtl.port }}
      name: http
  selector:
    app: bigid-reporting-etl
{{- end }}
