{{- if .Values.global.bigid.dataCatalog.autoscaling.enabled }}
{{- if $.Capabilities.APIVersions.Has "autoscaling/v2/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: bigid-data-catalog
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-data-catalog
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "data-catalog.labels" . | nindent 4 }}
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: {{ .Values.global.bigid.dataCatalog.autoscaling.scaleDownPolicy.periodSeconds }}
        type: Percent
        value: {{ .Values.global.bigid.dataCatalog.autoscaling.scaleDownPolicy.value }}
      stabilizationWindowSeconds: {{ .Values.global.bigid.dataCatalog.autoscaling.scaleDownPolicy.stabilizationWindowSeconds }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bigid-data-catalog
  minReplicas: {{ .Values.global.bigid.dataCatalog.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.global.bigid.dataCatalog.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.global.bigid.dataCatalogConsumer.create }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.global.bigid.dataCatalog.autoscaling.targetCPUUtilizationPercentage }}
    {{- else }}
    - type: Object
      object:
        describedObject:
          kind: Pod
          name: '*'
        metric:
          name: catalog_queue
        target:
          averageValue: {{ .Values.global.bigid.dataCatalog.autoscaling.averageValue }}
          type: AverageValue
          value: "1"
    {{- end }}
{{- end }}
