{{- if .Values.global.bigid.dataCatalogConsumer.create -}}
{{- if .Values.global.bigid.dataCatalogConsumer.autoscaling.enabled -}}
{{- if $.Capabilities.APIVersions.Has "keda.sh/v1alpha1" }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: bigid-data-catalog-consumer-trigger-auth
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretTargetRef:
    - parameter: host
      name: bigid-auth-secret
      key: rabbitmq-host
{{- end }}
{{- end }}
{{- end }}
