{{- if and (.Values.mongodb.tls.enabled) (.Values.mongodb.enabled) }}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-certs-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook-weight: "1"
rules:
- apiGroups: [""]
  resources: [ "secrets" ]
  verbs: [ "create", "get", "patch" ]
{{- end }}
