{{- if and (.Values.mongodb.tls.enabled) (.Values.mongodb.enabled) }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-certs-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook-weight: "2"
subjects:
- kind: ServiceAccount
  name: mongodb-certs-job
  apiGroup: ""
roleRef:
  kind: Role
  name: mongodb-certs-job
  apiGroup: rbac.authorization.k8s.io
{{- end }}
