{{- if and (.Values.mongodb.tls.enabled) (.Values.mongodb.enabled) }}
{{- $cn := printf "bigid-mongodb.%s.svc.cluster.local" .Release.Namespace }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-self-signed-certs
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- $ca:= genCA "myMongo-ca" 3650 }}
  {{- $cert := genSignedCert $cn nil nil 3650 $ca }}
  {{- $pem := printf "%s%s" $cert.Cert $cert.Key }}
  mongodb-ca-cert: {{ b64enc $ca.Cert }}
  mongodb-ca-key: {{ b64enc $ca.Key }}
  client-pem: {{ b64enc $pem }}
{{- end }}
