{{- if and (.Values.mongodb.tls.enabled) (.Values.mongodb.enabled) }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: mongodb-certs-job
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    helm.sh/hook-weight: "1"
{{- end }}
