global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  podAnnotations: {}
  bigid:
    ## @param global.bigid.containerSecurityContext Security Context for BigID containers
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
    ## @param global.bigid.podSecurityContext Security Context for BigID pods
    podSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsGroup: 1001
    catalogProcessor:
      create: false
      replicaCount: 1
      image:
        repository: "bigid-catalog-processor"
      serviceAccount:
        create: true
      podAnnotations: {}
      JavaOpts: ""
      port: 8099
      diffHistoryQueue:
        enabled: false
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      resources:
        requests:
          memory: 500Mi
          cpu: 250m
        limits:
          memory: 4Gi
          cpu: 3
      heapSizePercent: 85
