{{- if .Values.global.bigid.metadataSearch.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigid-metadata-search
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-metadata-search
  {{- with .Values.global.bigid.metadataSearch.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
