{{- if .Values.enabled }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alation.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "alation.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
automountServiceAccountToken: false
{{- end }}
