global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param podAnnotations Annotations for BigiD pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  podAnnotations: {}
  bigid:
    confluent:
      replicaCount: 1
      securityContext: {}
      serviceAccount:
        create: true
        annotations: {}
      resources:
        requests:
          memory: "3Gi"
          cpu: "1"
        limits:
          memory: "16Gi"
          cpu: "4"
      containerSecurityContext:
        enabled: false
      podSecurityContext:
        enabled: false
      ports:
        zookeeper: 2181
        landoop: 3030
        kafka: 9092
        rest: 8083
        registry: 8081
        jmx: 9581
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
