apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ignite.fullname" . }}
  labels:
    {{- include "ignite.labels" . | nindent 4 }}
data:
  node-configuration.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <beans xmlns="http://www.springframework.org/schema/beans"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="
            http://www.springframework.org/schema/beans
            http://www.springframework.org/schema/beans/spring-beans.xsd">
        <bean class="org.apache.ignite.configuration.IgniteConfiguration">
            <!-- Enable peer class loading. -->
            <property name="peerClassLoadingEnabled" value="true"/>

            <property name="discoverySpi">
                <bean class="org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi">
                    <property name="ipFinder">
                        <bean class="org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder">
                            <property name="serviceName" value="{{ include "ignite.fullname" . }}"/>
                            <property name="namespace" value="{{ .Release.Namespace }}"/>
                        </bean>
                    </property>
                </bean>
            </property>
            <property name="dataStorageConfiguration">
                    <bean class="org.apache.ignite.configuration.DataStorageConfiguration">
                        <property name="defaultDataRegionConfiguration">
                            <bean class="org.apache.ignite.configuration.DataRegionConfiguration">
                                <!-- enable mertrics for the default data region -->
                                <property name="metricsEnabled" value="true"/>
                                <!-- other properties -->
                                <property name="maxSize" value="#{ {{ include "ignite.calcMaxSize" . }} }"/>
                            </bean>
                        </property>
                    </bean>
            </property>
        </bean>
    </beans>
