{{- if and (.Values.global.bigid.scanner.remote.enabled ) (.Values.global.bigid.scanner.fipsMode.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: bigid-fips-cert
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  ca.cert: {{ .Files.Get "certs/ca.cert" | b64enc }}
{{- end }}
