{{- if or .Values.global.bigid.multiTenantMode.enabled .Values.global.bigid.scanner.tinyScanner.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigid-tiny-scanner
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-tiny-scanner
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.global.bigid.scanner.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{ include "global.skipCheckovAnnotations" . | nindent 4 }}
    {{- with .Values.global.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.global.bigid.scanner.tinyScanner.replicaCount }}
  selector:
    matchLabels:
      app: bigid-tiny-scanner
    {{- with .Values.global.podLabels }}
      {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- if .Values.global.bigid.scanner.updateStrategy }}
  strategy: {{- toYaml .Values.global.bigid.scanner.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.bigid.scanner.tinyScanner.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: bigid-tiny-scanner
      {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if and (.Values.global.apm.enabled) (eq .Values.global.apm.type "datadog") }}
        tags.datadoghq.com/bigid-tiny-scanner.env: {{ .Release.Namespace }}
        tags.datadoghq.com/bigid-scanner.service: bigid-tiny-scanner
        tags.datadoghq.com/service: "bigid-tiny-scanner"
        tags.datadoghq.com/version: "{{ .Values.global.image.tag | trunc 63 }}"
      {{- end }}
    spec:
      {{- if .Values.global.bigid.scanner.serviceAccount.create }}
      serviceAccountName: bigid-scanner
      automountServiceAccountToken: false
      {{- end }}
      volumes:
      {{- with .Values.global.bigid.scanner.extraVolumes }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.global.scannerAffinity }}
      affinity:
        {{ tpl .Values.global.scannerAffinity . | nindent 8 | trim }}
      {{- end }}
      containers:
      {{- with .Values.global.bigid.scanner.sidecars }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
      - image: "{{ .Values.global.image.repository }}/{{.Values.global.bigid.scanner.image.repository}}{{ template "bigid.scannerArmRepository" . }}:{{ .Values.global.image.tag }}"
        securityContext:
          {{- toYaml .Values.global.bigid.scanner.securityContext | nindent 10 }}
        resources:
          {{- toYaml .Values.global.bigid.scanner.tinyScanner.resources | nindent 10 }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        name: bigid-tiny-scanner
        ports:
        - containerPort: 9999
        envFrom:
        - configMapRef:
            name: apm-configuration
        {{- if .Values.global.extraEnvVarsCM }}
        - configMapRef:
            name: {{ .Values.global.extraEnvVarsCM }}
        {{- end }}
        {{- if .Values.global.extraEnvVarsSecret }}
        - secretRef:
            name: {{ .Values.global.extraEnvVarsSecret }}
        {{- end }}
        env:
        {{- with .Values.global.extraEnvVars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: CLASSIFICATION_SNIPPET_ENABLED
          value: {{ .Values.global.bigid.snippetPersister.create | quote }}
        - name: BIGID_GIT_HASH
          {{- if .Values.global.bigid.scanner.remote.enabled }}
          value: {{ include "bigid.githash" . | quote }}
          {{- else }}
          valueFrom:
            configMapKeyRef:
              name: global-configuration
              key: BIGID_GIT_HASH
          {{- end }}
        - name: BIGID_DATE
          value: {{ now | date "2006-01-02" | quote }}
        - name: BIGID_VERSION
        {{- if and (eq .Values.global.bigid.installationType "kots") .Values.global.bigid.scanner.remote.enabled }}
          value: "{{ .Values.global.image.tag }}_KOTS"
        {{- else }}
          value: {{ .Values.global.image.tag | quote }}
        {{- end }}
        {{- if and (.Values.global.apm.enabled) (eq .Values.global.apm.type "datadog") }}
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_ENV
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/bigid-scanner.env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['tags.datadoghq.com/bigid-scanner.service']
        {{- end }}
        - name: LABELER_ENABLED
          value: "{{ .Values.global.bigid.labeler.create }}"
        - name: SCANNER_JAVA_OPTS
          value: {{ printf "$(SCANNER_JAVA_APM_OPTS) %s" (include "java.calcScannerHeapSize" .Values.global.bigid.scanner) | quote }}
        - name: NFS_V4_PROTOCOL
          value: "{{ .Values.global.bigid.scanner.nfsV4.enabled }}"
        - name: IS_SCANNER_BLOCKED_BY_CONFIG_SERVICE
          value: "{{ .Values.global.bigid.scanner.isScannerBlockedByConfigService }}"
        - name: ORCH_CLIENT_MAX_CONNECTION_PER_ROUTE
          value: "{{ .Values.global.bigid.scanner.orchClientMaxConnectionPerRoute }}"
        - name: ORCH_CLIENT_MAX_CONNECTION_TOTAL
          value: "{{ .Values.global.bigid.scanner.orchClientMaxConnectionTotal }}"
        - name: INTERNAL_METADATA_PROCESSING_THREADS
          value: "{{ .Values.global.bigid.scanner.internalMetadataProcessingThreads }}"
        - name: THREAD_POOL_SIZE
          value: "{{ .Values.global.bigid.scanner.threadPoolSize }}"
        - name: SCANNER_THREADS
          value: "{{ .Values.global.bigid.scanner.threadSize }}"
        - name: TEST_CONNECTION_SYNC_THREADS
          value: "{{ .Values.global.bigid.scanner.testConnection.threadSize }}"
        - name: TEST_CONNECTION_SYNC_THREADS_MAX
          value: "{{ .Values.global.bigid.scanner.testConnection.threadMaxSize }}"
        - name: TEST_CONNECTION_EXECUTOR_QUEUE_SIZE
          value: "{{ .Values.global.bigid.scanner.testConnection.queueSize }}"
        - name: SCANNER_MAX_THREADS
          value: "{{ .Values.global.bigid.scanner.threadMaxSize }}"
        - name: ORCH_ASYNCH
          value: "true"
        - name: BIGID_ORCH_HOST
          value: "bigid-orch"
        - name: BIGID_ORCH_PORT
          value: "{{ .Values.global.bigid.orchestrator.port }}"
        - name: BIGID_ORCH_PROTOCOL
          value: http
        {{- if or (.Values.global.bigid.ner.create) (.Values.global.bigid.clustering.create) }}
        - name: CLUSTERING_ENABLED
          value: "true"
        {{- end }}
        - name: NER_CLASSIFIER_ENABLED_FEATURE_FLAG
          value: "false"
        - name: DATA_PREVIEW_DISABLED
          value: {{ .Values.global.bigid.scanner.dataPreviewDisabled | quote }}
        - name: DISCOVERY_ENGINE_ALGORITHM
          value: "{{ .Values.global.bigid.scanner.discoveryEngineAlgorithm }}"
        - name: BIGID_UI_API
          value: "/api/v1/"
        - name: ENABLED_SCAN_MANAGERS
        {{- if .Values.global.bigid.multiTenantMode.enabled }}
          value: "{{ .Values.global.bigid.scanner.tinyScanner.enabledScanManagersMt }}"
        {{- else }}
          value: "{{ .Values.global.bigid.scanner.tinyScanner.enabledScanManagers }}"
        {{- end }}
        - name: BIGID_TENANT_ID
          value: {{ .Values.global.bigid.scanner.tinyScanner.tenantId | quote }}
        {{- if (not .Values.global.bigid.scanner.remote.enabled) }}
        - name: MULTI_TENANT_MODE_ENABLED
          value: {{ .Values.global.bigid.multiTenantMode.enabled | quote }}
        {{- if .Values.global.bigid.multiTenantMode.enabled }}
        - name: SCANNER_TYPE
          value: "shared"
        {{- end }}
        - name: BIGID_UI_PORT
          value: "{{ .Values.global.bigid.web.port }}"
        - name: BIGID_UI_PROTOCOL_EXT
          value: "http"
        - name: BIGID_UI_HOST_EXT
          value: "bigid-web"
        {{- else }}
        - name: BIGID_UI_PORT
          value: "443"
        - name: BIGID_UI_PROTOCOL_EXT
          value: "https"
        - name: BIGID_UI_HOST_EXT
          value: "{{ .Values.global.ingress.bigidHost }}"
        - name: BIGID_REFRESH_TOKEN
          value: {{ .Values.global.bigid.scanner.refreshToken }}
        - name: IS_REMOTE_SCANNER
          value: "true"
        - name: SCANNER_GROUP_NAME
          value: {{ .Values.global.bigid.scanner.groupName }}
        - name: SCANNER_HOST_NAME
          value: "defaultHostNameAlive"
        {{- end }}
        - name: HEALTH_MSG_LOG_RATE_BY_HEALTH_EVENT_COUNT
          value: "{{ .Values.global.bigid.scanner.tinyScanner.healthMsgLogRage }}"
        - name: SET_SAP_SECUDIR
          value: "{{ .Values.global.bigid.scanner.set_sap_secudir }}"
        - name: USE_OJDBC7
          value: "{{ .Values.global.bigid.scanner.use_ojdbc7 }}"
        - name: USE_DB2_JCC3
          value: "{{ .Values.global.bigid.scanner.use_db2_jcc3 }}"
        - name: USE_SAS
          value: "{{ .Values.global.bigid.scanner.use_sas }}"
        - name: PROXY_SSL_CERTIFICATE
          value: ""
        - name: BIGID_HTTP_CLIENT_INFINITE_RETRIES
          value: "true"
        - name: ENCRYPT_PAYLOAD
          value: {{ .Values.global.bigid.scanner.encryptPayload | quote }}
        - name: PAYLOAD_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: payload-enc-key
              key: payloadEncKey
              optional: true
        readinessProbe:
          httpGet:
            path: /actuator/readiness
            port: 9999
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9999
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        {{- with .Values.global.bigid.scanner.extraVolumeMounts }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- if .Values.global.bigid.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.global.bigid.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      nodeSelector:
      {{- $affinity := fromYaml .Values.global.scannerAffinity }}
      {{- if not $affinity.nodeAffinity }}
      {{- if .Values.global.bigid.scanner.nodeSelector }}
        {{- toYaml .Values.global.bigid.scanner.nodeSelector | nindent 8 }}
      {{- else }}
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      {{- end }}
{{- end }}
