apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigid-orch2
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-orch2
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "orchestrator2.labels" . | nindent 4 }}
  annotations:
    {{ include "global.skipCheckovAnnotations" . | nindent 4 }}
    {{- with .Values.global.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.global.bigid.orchestrator2.replicaCount }}
  selector:
    matchLabels:
      app: bigid-orch2
      {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- if .Values.global.bigid.orchestrator2.updateStrategy }}
  strategy: {{- toYaml .Values.global.bigid.orchestrator2.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
      {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.bigid.orchestrator2.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: bigid-orch2
        {{- with .Values.global.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if and (.Values.global.apm.enabled) (eq .Values.global.apm.type "datadog") }}
        tags.datadoghq.com/bigid-orch2.env: {{ .Release.Namespace }}
        tags.datadoghq.com/bigid-orch2.service: bigid-orch2
        tags.datadoghq.com/service: "bigid-orch2"
        tags.datadoghq.com/version: "{{ .Values.global.image.tag | trunc 63 }}"
      {{- end }}
    spec:
      {{- include "deploymentSpec-tpl" . | nindent 6 }}
