version: "3.2"
services:
  bigid-snippet-persister:
    image: bigid/bigid-snippet-persister${BIGID_ENV}
    hostname: bigid-snippet-persister
    container_name: bigid-snippet-persister
    ports:
      - "9990:9990"
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_ENV_VARS
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC
      - BIGID_TENANT_ID
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - BIGID_CACHE_PASSWORD=password
      - ORCHESTRATOR_URL
      - LOG_LEVEL
      - BIGID_CONFIG_URL
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_UI_PROTOCOL_EXT
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-postgres}
      - BIGID_APP_ACCESS_TOKEN
      - SNIPPET_PERSISTER_JVM_SSL_OPTS
      - PERSIST_SERVICE_PORT
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=5432
      - DATABASE_REGION
      - POSTGRES_ROLE_ARN=${POSTGRES_ROLE_ARN}
      - POSTGRES_AUTH=${DB_AUTH_METHOD:-AWS_SECRET_MANAGER}
      - AWS_POSTGRES_SECRET_ID=${AWS_POSTGRES_SECRET_ID}
      - DATABASE_ENDPOINT=${DATABASE_ENDPOINT}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA:-public}
      - BIGID_UI_PORT=${BIGID_UI_PORT_EXT:-443}
      - USE_HEALTH_CHECK=${USE_HEALTH_CHECK:-false}
      - SNIPPET_HTTP_SIMULATOR_ENABLED=false
      - HIKARI_MAX_LIFETIME=${HIKARI_MAX_LIFETIME:-90000}
      - HIKARI_CONNECTION_TIMEOUT=${HIKARI_CONNECTION_TIMEOUT:-150000}
      - HIKARI_MAX_POOL_SIZE=${HIKARI_MAX_POOL_SIZE:-100}
    restart: always
