version: '3.2'

services:
  bigid-ner-hadoop:
    image: bigid/bigid-ner${BIGID_ENV}
    expose:
      - "8080"
    container_name: bigid-ner-hadoop
    user: bigid
    hostname: bigid-ner-hadoop
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - PRINT_NER_TO_LOG
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_UI_PROTOCOL_EXT
      - BIGID_UI_API
      - NER_LOG_FEATURE_FLAG
      - BIGID_USER
      - BIGID_PASSWORD
      - BIGID_REFRESH_TOKEN
      - ENV_FOR_DYNACONF=${ENV_FOR_DYNACONF:-prod}
      - NER_EXTRACT_ENTITIES_LANGUAGE_SPECIFIC
      - NER_DOC_CLF_OOTB_LANGUAGE_SPECIFIC
      - NER_DOC_CLF_OOTB_WHITELIST
      - NER_DOC_CLF_CUSTOM_WHITELIST
      - NER_LOG_LEVEL
      - STRUCTURED_NER_LEVEL=1
      - PYTHONUNBUFFERED=1
      - NER_MODEL
      - DISABLE_AUTO_UPGRADE_OF_CLASSIFIERS
      - ENCRYPT_PAYLOAD
      - PAYLOAD_ENCRYPTION_KEY
    volumes:
      - bigid-scanner-data:/ner_env/ner_models
    restart: always

  bigid-scanner-with-hadoop:
    links:
      - bigid-ner-hadoop
    environment:
      - CLUSTERING_ENABLED=true
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG=true
