version: "3.2"

services:
  bigid-ml-worker: &ml-base-service-ext-mongo-ssl
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PASS
    volumes:
      - type: bind
        source: ./mongo/ssl
        target: /etc/ssl/bigid
        read_only: true
  bigid-ml-gw:
    <<: *ml-base-service-ext-mongo-ssl
  bigid-ml-scheduler:
    <<: *ml-base-service-ext-mongo-ssl
