version: "3.2"

services:
  bigid-ml-worker: &ml-base-service
    container_name: bigid-ml-worker
    image: bigid/bigid-ml${BIGID_ENV}
    hostname: bigid-ml
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - MONGO_EXTERNAL_FULL_URL
      - SECRET_KEY
      - LOG_LEVEL
      - SIZE_OF_LOG_IN_BYTES
      - LOG_BACKUP_NUM
      - CLUSTERING_WORKER_NAME
      - CLUSTERING_SERVER_LOG_PATH
      - CLUSTERING_WORKER_LOG_PATH
      - CLUSTERING_WORKER_LOG_FILE_NAME
      - CLUSTERING_SERVER_LOG_FILE_NAME
      - CLUSTERING_SERVER_LOG_FORMAT
      - CLUSTERING_WORKER_LOG_GENERAL_FORMAT
      - CLUSTERING_WORKER_LOG_TASK_FORMAT
      - CLUSTERING_WORKER_NUMBER_OF_THREADS
      - CLUSTERING_HTTP_LOG_SUPPORT_FLAG
      - CLUSTERING_MQ_LOG_QUEUE
      - CLUSTERING_MQ_TOPIC
      - MQ_HOST
      - MQ_USERNAME
      - MQ_PASSWORD
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - SALT
      - ENV_FOR_DYNACONF
      - IS_REMOTE_SCANNER
      - HOTSPOTS_ENABLED
      - PAYLOAD_ENCRYPTION_KEY
      - CELERY_CONTROL_DISABLED
    tty: true
    entrypoint: /usr/local/bin/supervisord
    command: -c /cluster_package/supervisord.conf
    restart: always

  bigid-ml-gw:
    <<: *ml-base-service
    container_name: bigid-ml-gw
    expose:
      - "3300"
    entrypoint: /cluster_package/clustering-boot.sh
    command: -r SERVER

#  bigid-ml-mq-gw:
#    <<: *ml-base-service
#    container_name: bigid-ml-mq-gw
#    entrypoint: /cluster_package/clustering-boot.sh
#    command: -r MQ_SERVER

  bigid-ml-scheduler:
    <<: *ml-base-service
    container_name: bigid-ml-scheduler
    entrypoint: /cluster_package/clustering-boot.sh
    command: -r FAST_WORKER

  bigid-web:
    environment:
      - CLUSTERING_ENABLED=true
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG=true
      - AUDIT_FILE_MAX_SIZE
      - PRINT_AUDIT_TO_STDOUT
      - PAYLOAD_ENCRYPTION_KEY

  bigid-orch:
    environment:
      - CLUSTERING_ENABLED=true
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG=true
      - PAYLOAD_ENCRYPTION_KEY
      - STATE_MANAGEMENT_API_ENABLED

  bigid-orch2:
    environment:
      - CLUSTERING_ENABLED=true
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG=true
      - PAYLOAD_ENCRYPTION_KEY
      - STATE_MANAGEMENT_API_ENABLED

  bigid-scanner:
    environment:
      - CLUSTERING_ENABLED=true
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG=true
      - PAYLOAD_ENCRYPTION_KEY
