version: '3.2'
services:
  newrelic-infra:
    container_name: newrelic-infra
    image: newrelic/infrastructure-bundle:2.6.2
    cap_add:
      - SYS_PTRACE
    environment:
      - NRIA_CUSTOM_ATTRIBUTES={"monitoringCustomerName":"${MONITORING_CUSTOMER_NAME}"}
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY_VALUE}
      - NRIA_ENABLE_PROCESS_METRICS=true
      - MONGO_HOST=${BIGID_MONGO_HOST_EXT}
      - MONGO_PORT=${BIGID_MONGO_PORT_EXT}
      - MONGO_USERNAME=${BIGID_MONGO_MONITOR_USER}
      - MONGO_PASSWORD=${BIGID_MONGO_MONITOR_PASSWORD}
      - MONGO_AUTH_SOURCE=${BIGID_MONGO_AUTH_SOURCE_EXT}
      - MONGO_USE_SSL=${BIGID_MONGO_MONITOR_USE_SSL}
#    network_mode: "host"
    volumes:
      - ${PWD}/newrelic/integrations.d:/etc/newrelic-infra/integrations.d
      - ${PWD}/rabbitmq/certfiles:/etc/rabbitmq/certfiles
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
