version: "3.2"
services:
  bigid-metadata-search:
    image: bigid/bigid-metadata-search${BIGID_ENV}
    expose:
      - "8082"
    container_name: bigid-metadata-search
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_ENV_VARS
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_ELASTICSEARCH_HOST_EXT
      - BIGID_ELASTICSEARCH_PORT_EXT
      - BIGID_ELASTICSEARCH_EXTERNAL_FULL_URL
      - BIGID_TENANT_ID
      - BIGID_ELASTICSEARCH_USER
      - BIGID_ELASTICSEARCH_PWD
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - LOG_LEVEL
      - MDSEARCH_MIN_REINDEX_PERIOD_MINUTES
      - MDSEARCH_INDEXING_TIMEOUT_MINUTES
      - MDSEARCH_CATALOG_UPLOADER_THREADS
      - MDSEARCH_UPLOADER_BULK_SIZE
      - MDSEARCH_CATALOG_CRON_SCHEDULE
      - MDSEARCH_DEFAULT_CRON_SCHEDULE
      - JDK_JAVA_OPTIONS=${JDK_MDSEARCH_JAVA_OPTIONS:--server -Xms4g -Xmx4g}
      - BIGID_ELASTICSEARCH_USE_SSL
      - BIGID_ELASTICSEARCH_SSL_CERT_PATH
      - BIGID_UI_PORT_EXT
      - BIGID_UI_PROTOCOL_EXT
      - SPRING_PROFILES_ACTIVE
      - BIGID_APP_ACCESS_TOKEN
      - BIGID_CACHE_PASSWORD
      - BIGID_MQ_USER
      - BIGID_MQ_PASSWORD
    hostname: bigid-metadata-search
    restart: always
