version: "3.2"

services:
  bigid-corr-new:
    image: bigid/bigid-corr-new${BIGID_ENV}
    container_name: bigid-corr-new
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
      - bigid-mq:${BIGID_MQ_HOST_EXT}
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_UI_HOST_EXT
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MQ_HOST_EXT
      - BIGID_IGNITE_HOST_EXT
      - BIGID_CORR_HOST_EXT
      - BIGID_CORR_CLIENT_MODE
      - MULTI_TENANT_MODE_ENABLED
      - NEW_CORR_JVM_OPTS
      - BIGID_CORR_CACHE_SIZE=${BIGID_CORR_CACHE_SIZE:-10}
      - NEW_CORR_JVM_SSL_OPTS
      - GENERATE_IDENTITIES_LOCAL
      - SPRING_PROFILES_ACTIVE
      - GENERATE_IDENTITIES_ON_START_UP
      - BIGID_UI_PORT_EXT
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - NUMBERS_LENGTH_THRESHOLD
      - CORRELATOR_HOST_NAME
      - CONFIGURATION_SERVICE_HOST_EXT
      - BIGID_ORCH_PROTOCOL
      - BIGID_ORCH_HOST
      - BIGID_ORCH_PORT
      - BIGID_USER
      - BIGID_REFRESH_TOKEN
      - BIGID_CONFIG_BASE_URL
    restart: always
