version: '3.2'

volumes:
    bigid-scanner-data:
      external: true

services:
  bigid-scanner:
    image: bigid/bigid-scanner${BIGID_ENV}
    expose:
      - "9999"
    container_name: bigid-scanner
    user: bigid
    hostname: bigid-scanner
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - FIPS_CERTIFICATE_PATH=${FIPS_CERTIFICATE_PATH:-/tmp/certs/ca.cert}
      - SCANNER_JAVA_OPTS
      - IS_SCANNER_BLOCKED_BY_CONFIG_SERVICE
      - IS_REMOTE_SCANNER=${IS_REMOTE_SCANNER:-true}
      - IGNORE_MEDIA_TYPE # list of Tika MediaType that overwrite as MediaType.TEXT_PLAIN
      - THREAD_POOL_SIZE  # Deprecated
      - SCANNER_THREADS
      - SCANNER_MAX_THREADS
      - JIT_SCAN_THREADS
      - DELETION_SCAN_THREADS
      - ORCH_ASYNCH
      - BIGID_USER
      - BIGID_PASSWORD
      - BIGID_REFRESH_TOKEN
      - SCANNER_HOST_NAME
      - SCANNER_GROUP_NAME
      - DISCOVERY_ENGINE_ALGORITHM
      - DATA_PREVIEW_DISABLED
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_UI_PROTOCOL_EXT
      - BIGID_UI_API
      - TZ
      - ENABLE_GENERIC_REST_API_CONNECTOR=${ENABLE_GENERIC_REST_API_CONNECTOR:-false}
      - SET_SAP_SECUDIR
      - USE_OJDBC7
      - USE_DB2_JCC3
      - USE_SAS
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - MICROSOFT_GRAPH_API_PAGE_SIZE
      - DISABLE_NFS_AUTOMOUNT
      - NFS_V4_PROTOCOL
      - MAX_HOURS_FOR_DISCOVERY_ENGINE_CACHE
      - BIGID_KERBEROS_SPNEGO_AUTH_ENABLED=${BIGID_KERBEROS_SPNEGO_AUTH_ENABLED:-false}
      - KRB5_CONFIG
      - REMOTE_SCANNER_VAULT_CUSTOM_HEADER_NAME
      - REMOTE_SCANNER_VAULT_CUSTOM_HEADER_VALUE
      - BIGID_HTTP_CLIENT_INFINITE_RETRIES
      - ENCRYPT_PAYLOAD=${ENCRYPT_PAYLOAD:-false}
      - PAYLOAD_ENCRYPTION_KEY
      - IS_FIPS_MODE=${IS_FIPS_MODE:-false}
      - ORCH_CLIENT_MAX_CONNECTION_PER_ROUTE=${ORCH_CLIENT_MAX_CONNECTION_PER_ROUTE:-24}
      - ORCH_CLIENT_MAX_CONNECTION_TOTAL=${ORCH_CLIENT_MAX_CONNECTION_TOTAL:-34}
      - INTERNAL_METADATA_PROCESSING_THREADS=${INTERNAL_METADATA_PROCESSING_THREADS:-21}
      - METADATA_UPDATE_BY_BULK_ENABLED=${METADATA_UPDATE_BY_BULK_ENABLED:-false}
      - CLASSIFICATION_SNIPPET_ENABLED=${CLASSIFICATION_SNIPPET_ENABLED:-false}
      - SNIPPET_CLIENT_TIMEOUT_MS=${SNIPPET_CLIENT_TIMEOUT_MS:-180000}
      - CLASSIFICATION_SNIPPET_SERVER_HOSTNAME=${CLASSIFICATION_SNIPPET_SERVER_HOSTNAME:-bigid-snippet-persister:443}
      - CLASSIFICATION_SNIPPET_PROTOCOL=${CLASSIFICATION_SNIPPET_PROTOCOL:-https}
      - SNIPPET_API_BATCH_SIZE=${SNIPPET_API_BATCH_SIZE:-500}
      - BIGID_HTTP_TIMEOUT_MILLIS
    privileged: ${ENABLE_PRIVILEGED_SCANNER:-true}
    volumes:
      - bigid-scanner-data:/etc/scanner
    restart: always
