version: "3.2"

services:
  ignite-master:
    image: apacheignite/ignite:2.8.1
    container_name: ignite-master
    environment:
      - OPTION_LIBS=ignite-rest-http
      - JVM_OPTS=-Xms5g -Xmx5g -server -XX:+AggressiveOpts
      - CONFIG_URI=file:///ignite/ignite-configuration.xml
      - IGNITE_QUIET=false
    ports:
      - "11211:11211" # JDBC port number.
      - "47100-47200:47100-47200" # communication SPI port number.
      - "47500-47509:47500-47509" # discovery SPI port number.
      - "48100-48200:48100-48200" # shared memory port
      - "8080:8080" # REST port number.
      - "10901:10900" #Thin clients port number.
      - "10800:10800"
    volumes:
      - ./ignite/ignite-configuration.xml:/ignite/ignite-configuration.xml:ro
    restart: always

  bigid-corr-new-master:
    image: bigid/bigid-corr-new${BIGID_ENV}
    container_name: bigid-corr-new-master
    depends_on:
      - ignite-master
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
      - bigid-mq:${BIGID_MQ_HOST_EXT}
      - bigid-ui:${BIGID_UI_HOST_EXT}
    environment:
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MQ_HOST_EXT
      - BIGID_IGNITE_HOST_EXT
      - BIGID_CORR_HOST_EXT
      - BIGID_CORR_CLIENT_MODE
      - MULTI_TENANT_MODE_ENABLED
      - NEW_CORR_JVM_OPTS
      - BIGID_CORR_CACHE_SIZE=${BIGID_CORR_CACHE_SIZE:-10}
      - NEW_CORR_JVM_SSL_OPTS
      - GENERATE_IDENTITIES_LOCAL
      - SPRING_PROFILES_ACTIVE
      - GENERATE_IDENTITIES_ON_START_UP
      - BIGID_UI_PORT_EXT
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - NUMBERS_LENGTH_THRESHOLD
      - CORRELATOR_HOST_NAME
    restart: always

  bigid-corr-new-client-1:
    image: bigid/bigid-corr-new${BIGID_ENV}
    container_name: bigid-corr-new-client-1
    depends_on:
      - ignite-master
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
      - bigid-mq:${BIGID_MQ_HOST_EXT}
      - bigid-ui:${BIGID_UI_HOST_EXT}
    environment:
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MQ_HOST_EXT
      - BIGID_IGNITE_HOST_EXT
      - BIGID_CORR_HOST_EXT
      - BIGID_CORR_CLIENT_MODE
      - NEW_CORR_JVM_OPTS
      - BIGID_CORR_CACHE_SIZE=${BIGID_CORR_CACHE_SIZE:-10}
      - NEW_CORR_JVM_SSL_OPTS
      - GENERATE_IDENTITIES_LOCAL
      - SPRING_PROFILES_ACTIVE
      - GENERATE_IDENTITIES_ON_START_UP
      - MULTI_TENANT_MODE_ENABLED
      - BIGID_UI_PORT_EXT
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - NUMBERS_LENGTH_THRESHOLD
      - CORRELATOR_HOST_NAME
    restart: always
