version: '3.2'
services:
  bigid-data-catalog-consumer:
    environment:
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
    volumes:
      - type: bind
        source: ./mongo/ssl
        target: /etc/ssl/bigid
        read_only: true
