version: '3.2'

volumes:
  bigid-mq-data:
    external: true

services:
  bigid-mq:
    image: rabbitmq:3.12.12-management
    user: rabbitmq
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
    container_name: bigid-mq
    hostname: rabbitmq
    volumes:
      - bigid-mq-data:/etc/rabbitmq
      - bigid-mq-data:/var/lib/rabbitmq/mnesia
    environment:
      - TZ
    restart: always
