version: '3.2'

services:
  bigid-config-service:
    image: bigid/bigid-config-service${BIGID_ENV}
    ports:
      - "${config_service_PORT:-3004}:${config_service_PORT:-3004}"
    container_name: bigid-config-service
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_ENV_VARS
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - PORT=${config_service_PORT}
      - LOG_LEVEL
      - CONFIG_SERVICE_JVM_OPTS
      - CONFIG_SERVICE_JVM_SSL_OPTS
      - BOOLEAN_SERVICES_MAP=${BOOLEAN_SERVICES_MAP:-false}
      - CONFIG_SERVICE_REDIS_CACHE=${CONFIG_SERVICE_REDIS_CACHE:-false}
#    network_mode: "host"
    hostname: bigid-config-service
    cap_add:
      - SYS_ADMIN
    restart: always
