version: '3.2'

volumes:
    bigid-scanner-data:
      external: true

services:
  bigid-scanner-with-hadoop:
    image: bigid/bigid-scanner-with-hadoop${BIGID_ENV}
    expose:
      - "9999"
    container_name: bigid-scanner-with-hadoop
    user: bigid
    hostname: bigid-scanner-with-hadoop
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - SCANNER_JAVA_OPTS
      - IS_SCANNER_BLOCKED_BY_CONFIG_SERVICE
      - IS_REMOTE_SCANNER=${IS_REMOTE_SCANNER:-true}
      - IGNORE_MEDIA_TYPE # list of Tika MediaType that overwrite as MediaType.TEXT_PLAIN
      - THREAD_POOL_SIZE  # Deprecated
      - SCANNER_THREADS
      - SCANNER_MAX_THREADS
      - JIT_SCAN_THREADS
      - DELETION_SCAN_THREADS
      - ORCH_ASYNCH
      - BIGID_USER
      - BIGID_PASSWORD
      - BIGID_REFRESH_TOKEN
      - BIGID_NER_HOST=${BIGID_NER_HOST:-bigid-ner-hadoop}
      - SCANNER_HOST_NAME
      - SCANNER_GROUP_NAME=${SCANNER_GROUP_NAME:-SCANNER_WITH_HADOOP_GROUP}
      - DISCOVERY_ENGINE_ALGORITHM
      - DATA_PREVIEW_DISABLED
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_UI_PROTOCOL_EXT
      - BIGID_UI_API
      - HADOOP_DIST
      - SPARK_SCANNER
      - TZ
      - ENABLE_GENERIC_REST_API_CONNECTOR=${ENABLE_GENERIC_REST_API_CONNECTOR:-false}
      - SET_SAP_SECUDIR
      - USE_OJDBC7
      - USE_DB2_JCC3
      - USE_SAS
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - MICROSOFT_GRAPH_API_PAGE_SIZE
      - DISABLE_NFS_AUTOMOUNT
      - NFS_V4_PROTOCOL
      - MAX_HOURS_FOR_DISCOVERY_ENGINE_CACHE
      - BIGID_KERBEROS_SPNEGO_AUTH_ENABLED=${BIGID_KERBEROS_SPNEGO_AUTH_ENABLED:-false}
      - KRB5_CONFIG
      - ENCRYPT_PAYLOAD
      - PAYLOAD_ENCRYPTION_KEY
      - BIGID_HTTP_CLIENT_INFINITE_RETRIES
    privileged: ${ENABLE_PRIVILEGED_SCANNER:-true}
    volumes:
      - bigid-scanner-data:/etc/scanner
    restart: always
