version: '3.2'
services:
  bigid-data-catalog:
    image: bigid/bigid-data-catalog${BIGID_ENV}
    expose:
      - "3555"
    container_name: bigid-data-catalog
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - PORT=${DATA_CATALOG_PORT}
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - SECRET_KEY
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - MONGO_EXTERNAL_FULL_URL
      - ORCHESTRATOR_URL
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MQ_HOST_EXT
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - LOG_LEVEL
      - BIGID_CONFIG_URL
      - STATE_MANAGEMENT_API_ENABLED
    hostname: bigid-data-catalog
    restart: always
