version: "3.2"
services:
  bigid-process-manager:
    image: bigid/bigid-process-manager${BIGID_ENV}
    hostname: bigid-process-manager
    container_name: bigid-process-manager
    links:
      - bigid-cache
    expose:
      - "3006"
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_ENV_VARS
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - MONGO_EXTERNAL_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC
      - BIGID_TENANT_ID
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - BIGID_CACHE_PASSWORD=password
      - ORCHESTRATOR_URL
      - LOG_LEVEL
      - BIGID_CONFIG_URL
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIGID_UI_PROTOCOL_EXT
      - SPRING_PROFILES_ACTIVE
      - BIGID_APP_ACCESS_TOKEN
      - PROCESS_MANAGER_JVM_SSL_OPTS
    restart: always
