version: '3.2'

volumes:
    bigid-mongo-data:
      external: true
    bigid-mq-data:
      external: true
    bigid-scanner-data:
      external: true
    bigid-web-data:
      external: false

services:
  bigid-ui:
    image: bigid/bigid-ui${BIGID_ENV}
    ports:
      - "443:443"
    links:
      - bigid-web
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - TZ
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
    container_name: bigid-ui
    volumes:
      - ./bigid-ui/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  bigid-web:
    image: bigid/bigid-web${BIGID_ENV}
    expose:
      - "3000"
    links:
     - bigid-mongo
     - bigid-mq
     - bigid-cache
     - bigid-orch
     - bigid-data-catalog
    container_name: bigid-web
    volumes:
      - bigid-web-data:/usr/src/app/log
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - SECRET_KEY
      - AUTH_SECRET_KEY
      - TOKEN_EXPIRATION_IN_MINUTES
      - UI_IDLE_TIMEOUT_IN_MINUTES
      - RESIDENCY_STATES_FIRST
      - MONGO_EXTERNAL_FULL_URL
      - TZ
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - BIG_ID_REPORT_LANGUAGE
      - BIGID_PRODUCT_TYPE
      - ENTITY_LEVEL_TAGGING_SUPPORTED
      - USE_EXTENDED_PERMISSIONS
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - MICROSOFT_GRAPH_API_PAGE_SIZE
      - IS_CI=${IS_CI}
      - AUDIT_FILE_MAX_SIZE
      - PRINT_AUDIT_TO_STDOUT
      - METADATA_CLASSIFIER_ENABLED
      - SCAN_API_ENABLED
      - DIM_ENABLED
      - USE_SAAS=${USE_SAAS:-false}
      - OKTA_DOMAIN
      - OKTA_API_TOKEN
      - OKTA_APPLICATION
      - OKTA_ROLE_GROUP_MAP
      - OKTA_MAX_USERS
      - BIGID_SCANNER_USER
      - BIGID_MONGO_REPLICASET
      - ENFORCE_STRONG_PASSWORD_SECURITY
      - PAYLOAD_ENCRYPTION_KEY
      - AMOUNT_OF_LOGS_FILE
      - AUTH0_TOKEN_CLAIMS_NAMESPACE
      - AUTH0_APP_NAME_ATTR_IN_TOKEN_CLAIMS
      - ORCH_CLIENT_MAX_CONNECTION_PER_ROUTE=${ORCH_CLIENT_MAX_CONNECTION_PER_ROUTE:-24}
      - ORCH_CLIENT_MAX_CONNECTION_TOTAL=${ORCH_CLIENT_MAX_CONNECTION_TOTAL:-34}
      - INTERNAL_METADATA_PROCESSING_THREADS=${INTERNAL_METADATA_PROCESSING_THREADS:-21}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bigid-web:3000/health/readiness"]
      interval: 20s
      timeout: 10s
      retries: 8

  bigid-orch:
    image: bigid/bigid-orch${BIGID_ENV}
    expose:
      - "3001"
    links:
      - bigid-mongo
#      - bigid-scanner
      - bigid-mq
      - bigid-cache

    container_name: bigid-orch
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - SECRET_KEY
      - AUTH_SECRET_KEY
      - APPLICATION_CREDENTIALS_KEY
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - ORCHESTRATOR_URL_EXT # If the Scanner is on a different Docker host, preferably Internal IP.
      - ORCHESTRATOR_URL_PUBLIC # Public IP: For Hadoop and EMR, in case Hadoop / EMR cluster are outside the VPC. If not set, hadoop callback URL will use ORCHESTRATOR_URL_EXT.
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - SAVE_SCANNED_IDENTITIES_AS_PII_FINDINGS
      - SCANNED_VALUES_IGNORE_LIST
      - TRUST_SELF_SIGNED_CERTS
      - IS_CALC_PSEUDO_PII
      - JIT_FILTER_LOW_CONFIDENCE_FACTOR
      - SAR_ONLY_STRICT_MATCHES
      - LINEAGE_ATTRIBUTES_BY_CONFIDENCE
      - TZ
      - METADATA_ACL_SCAN_ENABLED
      - DATA_SOURCE_ACL_SCAN_ENABLED
      - CORRELATION_RECOVERY_SCHEDULER_FLAG
      - GENERATE_IDENTITIES_ON_START_UP
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG
      - IDENTITY_RESOLUTION_ENABLED
      - RUN_RETENTION_POLICY_PROCESS
      - SCAN_PARTS_ENABLED
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - METADATA_CLASSIFIER_ENABLED
      - SCAN_API_ENABLED
      - BIGID_SCANNER_USER
      - IGNITE_CLUSTER_URL
      - BIGID_MONGO_REPLICASET
      - PAYLOAD_ENCRYPTION_KEY
      - AMOUNT_OF_LOGS_FILE
      - STATE_MANAGEMENT_API_ENABLED
      - METADATA_UPDATE_BY_BULK_SIZE= ${METADATA_UPDATE_BY_BULK_SIZE:-40}
      - USE_BACKPRESSURE_BULK_UPDATES= ${USE_BACKPRESSURE_BULK_UPDATES:-false}
    hostname: bigid-orch
    restart: always


  bigid-orch2:
    image: bigid/bigid-orch${BIGID_ENV}
    expose:
      - "3003"
    links:
      - bigid-mongo
      - bigid-scanner
      - bigid-mq
      - bigid-cache
    container_name: bigid-orch2
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - SECRET_KEY
      - MONGO_EXTERNAL_FULL_URL
      - ORCHESTRATOR_URL_EXT # If the Scanner is on a different Docker host, preferably Internal IP.
      - ORCHESTRATOR_URL_PUBLIC # Public IP: For Hadoop and EMR, in case Hadoop / EMR cluster are outside the VPC. If not set, hadoop callback URL will use ORCHESTRATOR_URL_EXT.
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - SAVE_SCANNED_IDENTITIES_AS_PII_FINDINGS
      - SCANNED_VALUES_IGNORE_LIST
      - TRUST_SELF_SIGNED_CERTS
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG
      - PORT=3003
      - IS_ORCH2=true
      - TZ
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - METADATA_CLASSIFIER_ENABLED
      - BIGID_MONGO_REPLICASET
      - PAYLOAD_ENCRYPTION_KEY
      - AMOUNT_OF_LOGS_FILE
      - STATE_MANAGEMENT_API_ENABLED
      - METADATA_UPDATE_BY_BULK_SIZE= ${METADATA_UPDATE_BY_BULK_SIZE:-40}
      - USE_BACKPRESSURE_BULK_UPDATES= ${USE_BACKPRESSURE_BULK_UPDATES:-false}
    hostname: bigid-orch2
    restart: always

  bigid-scanner:
    image: bigid/bigid-scanner${BIGID_ENV}
    expose:
      - "9999"
    container_name: bigid-scanner
    user: bigid
    hostname: bigid-scanner
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - SCANNER_JAVA_OPTS
      - IS_SCANNER_BLOCKED_BY_CONFIG_SERVICE
      - THREAD_POOL_SIZE  # Deprecated
      - IGNORE_MEDIA_TYPE # list of Tika MediaType that overwrite as MediaType.TEXT_PLAIN
      - SCANNER_THREADS
      - SCANNER_MAX_THREADS
      - JIT_SCAN_THREADS
      - DELETION_SCAN_THREADS
      - ORCH_ASYNCH
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - HADOOP_DIST
      - BIGID_USER
      - BIGID_PASSWORD
      - SCANNER_HOST_NAME
      - SCANNER_GROUP_NAME
      - DISCOVERY_ENGINE_ALGORITHM
      - DATA_PREVIEW_DISABLED
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - TZ
      - ENABLE_GENERIC_REST_API_CONNECTOR=${ENABLE_GENERIC_REST_API_CONNECTOR:-false}
      - SET_SAP_SECUDIR
      - USE_OJDBC7
      - USE_DB2_JCC3
      - USE_SAS
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - DISABLE_NFS_AUTOMOUNT
      - NFS_V4_PROTOCOL
      - ENCRYPT_PAYLOAD
      - PAYLOAD_ENCRYPTION_KEY
      - IS_FIPS_MODE=${IS_FIPS_MODE:-false}
    privileged: ${ENABLE_PRIVILEGED_SCANNER:-true}
    volumes:
      - bigid-scanner-data:/etc/scanner
#      - bigid-log-data:/usr/local/tomcat/logs
    restart: always


  bigid-mongo:
      image: mongo:${MONGODB_VERSION:-6.0}
      ports:
        - "27017:27017"
      volumes:
        - bigid-mongo-data:/data/db
      container_name: bigid-mongo
      environment:
        - TZ
        - NEW_RELIC_LICENSE_KEY_VALUE
        - MONITORING_CUSTOMER_NAME
        - TELEMETRY_ENABLED
        - NEW_RELIC_APM_ON
        - APPEND_TO_JSON_LOGS
      entrypoint:
        - mongod
        - --auth
        - --bind_ip_all
        - --replSet=bigid-replica-set
        - --keyFile=/data/db/replica-set.key
      restart: always

  bigid-cache:
    image: bitnami/redis:7.2.4
    expose:
      - "6379"
    container_name: bigid-cache
    environment:
      - REDIS_PASSWORD=password
      - REDIS_AOF_ENABLED=no
    command: /opt/bitnami/scripts/redis/run.sh --save ""
    restart: always

  bigid-mq:
    image: rabbitmq:3.12.12-management
    user: rabbitmq
    ports:
      - "15671:15671"
      - "5671:5671"
    container_name: bigid-mq
    hostname: rabbitmq
    volumes:
      - bigid-mq-data:/etc/rabbitmq
      - bigid-mq-data:/var/lib/rabbitmq/mnesia
    environment:
    - TZ
    - NEW_RELIC_LICENSE_KEY_VALUE
    - MONITORING_CUSTOMER_NAME
    - TELEMETRY_ENABLED
    - NEW_RELIC_APM_ON
    - APPEND_TO_JSON_LOGS
    restart: always

  bigid-corr-new:
    image: bigid/bigid-corr-new${BIGID_ENV}
    container_name: bigid-corr-new
    depends_on:
      - bigid-web
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_IGNITE_HOST_EXT
      - DELETE_PII_FINDINGS
      - MULTI_TENANT_MODE_ENABLED
      - BIGID_MONGO_DB_NAME
      - NEW_CORR_JVM_OPTS
      - BIGID_CORR_CACHE_SIZE=${BIGID_CORR_CACHE_SIZE:-4}
      - SPRING_PROFILES_ACTIVE
      - GENERATE_IDENTITIES_ON_START_UP
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - NUMBERS_LENGTH_THRESHOLD
      - TZ
      - BIGID_MONGO_REPLICASET
    restart: always
#    ports:
#      - 7082:7082
#      - 10800:10800 # SQL port number.
#      - 49112:49112 # JMX port number.
#      - 11211:11211
#      - 47100:47100 # communication SPI port number.
#      - 47400:47400
#      - "47500-47509:47500-47509" # discovery SPI port number.

  bigid-reports:
    image: bigid/bigid-reports${BIGID_ENV}
    expose:
      - "3005"
    container_name: bigid-reports
    depends_on:
      - bigid-config-service
      - bigid-mq
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - LOG_LEVEL
      - IS_PART_OF_BIGID=true
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - BIGID_MONGO_REPLICASET
    hostname: bigid-reports
    restart: always

  bigid-data-catalog:
    image: bigid/bigid-data-catalog${BIGID_ENV}
    expose:
      - "3555"
    links:
      - bigid-mongo
      - bigid-mq
      - bigid-orch
      - bigid-cache
    container_name: bigid-data-catalog
    depends_on:
      - bigid-orch
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - SECRET_KEY
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - LOG_LEVEL
      - BIGID_CONFIG_URL
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - BIGID_MONGO_REPLICASET
      - STATE_MANAGEMENT_API_ENABLED
    hostname: bigid-data-catalog
    restart: always

  bigid-config-service:
    image: bigid/bigid-config-service${BIGID_ENV}
    expose:
      - "3004"
    container_name: bigid-config-service
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_ENV_VARS
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_DB_NAME
      - CONFIG_SERVICE_JVM_OPTS
      - BIGID_MONGO_REPLICASET
      - BOOLEAN_SERVICES_MAP=${BOOLEAN_SERVICES_MAP:-false}
      - CONFIG_SERVICE_REDIS_CACHE=${CONFIG_SERVICE_REDIS_CACHE:-false}
    hostname: bigid-config-service
    restart: always

  bigid-action-center:
    image: bigid/bigid-action-center${BIGID_ENV}
    expose:
      - "3556"
    container_name: bigid-action-center
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - PORT=${ACTION_CENTER_PORT:-3556}
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - SECRET_KEY
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - MONGO_EXTERNAL_FULL_URL
      - ORCHESTRATOR_URL
      - BIGID_UI_HOST_EXT
      - BIGID_UI_PORT_EXT
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MQ_HOST_EXT
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - LOG_LEVEL
      - BIGID_CONFIG_URL
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_CA_PATH
    hostname: bigid-action-center
    restart: always
