version: "3.2"

services:
  bigid-aci:
    image: bigid/bigid-aci${BIGID_ENV}
    hostname: bigid-aci
    container_name: bigid-aci
    expose:
      - "4001"
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC
      - ACI_ORG_DOMAIN_LIST
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
    tty: true
    restart: always

  bigid-web:
    environment:
      - ACI_ENABLED=true

  bigid-orch:
    environment:
      - ACI_ENABLED=true

  bigid-orch2:
    environment:
      - ACI_ENABLED=true
