version: '3.2'

volumes:
    bigid-mongo-data:
      external: true

services:

  bigid-mongo:
    image: mongo:${MONGODB_VERSION:-6.0}
    ports:
      - "27017:27017"
    ulimits:
      nofile:
        soft: 500000
        hard: 1000000
    volumes:
      - bigid-mongo-data:/data/db
    container_name: bigid-mongo
    entrypoint:
      - mongod
      - --auth
      - --bind_ip_all
      - --tlsMode
      - requireTLS
      - --tlsCertificateKeyFile
      - /data/db/server.pem
      - --tlsCAFile
      - /data/db/ca.pem
      - --replSet=bigid-replica-set
      - --keyFile=/data/db/replica-set.key
    environment:
      - TZ
    restart: always
