version: '3.2'
services:
  bigid-web:
    environment:
      - LABELER_ENABLED=true
      - PAYLOAD_ENCRYPTION_KEY
  bigid-orch:
    environment:
      - LABELER_ENABLED=true
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - SCAN_API_ENABLED
      - DIM_ENABLED
      - PAYLOAD_ENCRYPTION_KEY
      - STATE_MANAGEMENT_API_ENABLED
  bigid-scanner:
    image: bigid/bigid-labeler${BIGID_ENV}
    environment:
      - LABELER_ENABLED=true
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - PROXY_SSL_CERTIFICATE
      - ENCRYPT_PAYLOAD
      - PAYLOAD_ENCRYPTION_KEY
      - HTTP_PROXY
      - HTTPS_PROXY
      - PROXY_SSL_CERTIFICATE
      - SSL_CERT_FILE
    restart: always
