version: '3.2'

volumes:
  bigid-mongo-data:
    external: false
  bigid-mq-data:
    external: true
  bigid-scanner-data:
    external: true
  bigid-web-data:
    external: false

services:
  bigid-orch2-consumer:
    image: bigid/bigid-orch${BIGID_ENV}
    expose:
      - "3023"
    links:
      - bigid-scanner
      - bigid-mq
      - bigid-cache
    container_name: bigid-orch2-consumer
    extra_hosts:
      - bigid-mongo:${BIGID_MONGO_HOST_EXT}
    environment:
      - BIGID_VERSION=${BIGID_VERSION:-release}
      - BIGID_DATE
      - BIGID_GIT_HASH
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - BIGID_MONGO_SSL
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - BIGID_REDIS_HOST
      - BIGID_REDIS_PORT
      - REDIS_PASSWORD
      - SECRET_KEY
      - MONGO_EXTERNAL_FULL_URL
      - ORCHESTRATOR_URL_EXT # If the Scanner is on a different Docker host, preferably Internal IP.
      - ORCHESTRATOR_URL_PUBLIC # Public IP: For Hadoop and EMR, in case Hadoop / EMR cluster are outside the VPC. If not set, hadoop callback URL will use ORCHESTRATOR_URL_EXT.
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC # Same as up.
      - SAVE_SCANNED_IDENTITIES_AS_PII_FINDINGS
      - SCANNED_VALUES_IGNORE_LIST
      - TRUST_SELF_SIGNED_CERTS
      - NER_CLASSIFIER_ENABLED_FEATURE_FLAG
      - PORT=3023
      - IS_ORCH2=true
      - TZ
      - NEW_RELIC_LICENSE_KEY_VALUE
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - NEW_RELIC_APM_ON
      - APPEND_TO_JSON_LOGS
      - METADATA_CLASSIFIER_ENABLED
      - PAYLOAD_ENCRYPTION_KEY
      - STATE_MANAGEMENT_API_ENABLED
      - DSAR_USE_CATALOG_COLUMNS_ENABLED_FF=${DSAR_USE_CATALOG_COLUMNS_ENABLED_FF:-true}
    hostname: bigid-orch2-consumer
    restart: always
