version: '3.2'

services:
  bigid-lineage:
    environment:
      - BIGID_MONGO_SSL_CA_PATH
      - BIGID_MONGO_SSL_CLIENT_CERT_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PATH
      - BIGID_MONGO_SSL_CLIENT_KEY_PASS
    volumes:
      - type: bind
        source: ./mongo/ssl
        target: /etc/ssl/bigid
        read_only: true
