version: "3.2"

services:
  bigid-collaboration:
    image: bigid/bigid-collaboration${BIGID_ENV}
    hostname: bigid-collaboration
    container_name: bigid-collaboration
    expose:
      - "4010"
    environment:
      - PORT=${COLLABORATION_PORT:-4010}
      - BIGID_MONGO_USER
      - BIGID_MONGO_PWD
      - MONGO_EXTERNAL_FULL_URL
      - MONGO_PUBLIC_FULL_URL
      - BIGID_MONGO_HOST_EXT
      - BIGID_MONGO_HOST_PUBLIC
      - BIGID_MQ_USER
      - BIGID_MQ_PWD
      - BIGID_MQ_HOST_EXT
      - SECRET_KEY
      - ORCHESTRATOR_URL
      - WEB_URL
      - MONITORING_CUSTOMER_NAME
      - TELEMETRY_ENABLED
      - LOG_LEVEL
      - BIGID_CONFIG_URL
    restart: always
    links:
      - bigid-mongo
      - bigid-mq
      - bigid-config-service
      - bigid-orch
