apiVersion: v1
kind: ConfigMap
metadata:
  name: global-configuration
  namespace: {{ .Release.Namespace | quote }}
data:
  BIGID_REDIS_SENTINEL_MODE: {{ .Values.redis.sentinel.enabled | quote }}
  BIGID_REDIS_REPLICAS_HOST_PREFIX: {{ include "redis.replicas.host.prefix" . | quote }}
  BIGID_REDIS_REPLICAS_HOST_SUFFIX: {{ include "redis.replicas.host.suffix" . | quote }}
  BIGID_REDIS_REPLICAS_NUMBER: {{ .Values.redis.replica.replicaCount | quote }}
  BIGID_REDIS_SENTINEL_PORT: {{ include "redis.sentinel.port" . | quote }}
  BIGID_REDIS_HOST: {{ .Values.redis.externalRedis.hostname | default "bigid-cache" | quote }}
  BIGID_REDIS_PORT: {{ .Values.redis.externalRedis.port | default "6379" | quote }}
  BIGID_CACHE_HOST_NAME: {{ .Values.redis.externalRedis.hostname | default "bigid-cache" | quote }}
  BIGID_CACHE_PORT: {{ .Values.redis.externalRedis.port | default "6379" | quote }}
  BIGID_MQ_HOST_EXT: {{ .Values.rabbitmq.externalRabbitmq.hostname | default "bigid-mq" | quote }}
  BIGID_MQ_PORT: {{ .Values.rabbitmq.externalRabbitmq.port | default "5671" | quote }}
  BIGID_VERSION: {{ .Values.global.image.tag | quote }}
  BIGID_GIT_HASH: {{ include "bigid.githash" . | quote }}
  BIGID_DATE: {{ now | date "2006-01-02" | quote }}
  TZ: {{ .Values.global.timeZone | quote }}
  BIGID_ELASTICSEARCH_HOST_EXT: {{ .Values.elasticsearch.master.servicenameOverride | quote }}
  BIGID_ELASTICSEARCH_PORT_EXT: {{ .Values.elasticsearch.port.http | quote }}
  BIGID_ELASTICSEARCH_EXTERNAL_FULL_URL: {{ .Values.elasticsearch.fullUrl | quote }}
  BIGID_ELASTICSEARCH_TENANT_ID: {{ .Values.elasticsearch.tenantId | quote }}
  BIGID_ELASTICSEARCH_USE_SSL: {{ .Values.elasticsearch.security.tls.restEncryption | quote }}
