{{- if not .Values.mongodb.externalMongo.existingAuthSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-base-configuration
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if .Values.mongodb.enabled }}
  BIGID_MONGO_SSL: {{ .Values.mongodb.tls.enabled | default "false" | toString | b64enc | quote }}
  MONGO_EXTERNAL_FULL_URL: {{ printf "mongodb://%s:%s@%s:27017/%s?authSource=admin&replicaSet=bigid-replica-set&ssl=%s" (toString .Values.mongodb.auth.rootUser) (toString .Values.mongodb.auth.rootPassword) (toString (.Values.mongodb.service.nameOverride | default "bigid-mongodb-headless")) (toString (.Values.mongodb.dbName | default "bigid-server")) (toString (.Values.mongodb.tls.enabled | default "false")) | b64enc | quote }}
  BIGID_MONGO_HOST_EXT: {{ .Values.mongodb.service.nameOverride | default "bigid-mongodb-headless" | b64enc | quote }}
  BIGID_MONGO_USER: {{ .Values.mongodb.auth.rootUser | toString | b64enc | quote }}
  BIGID_MONGO_PWD: {{ .Values.mongodb.auth.rootPassword | toString | b64enc | quote }}
  BIGID_MONGO_PORT: {{ .Values.mongodb.service.ports.mongodb | toString | b64enc | quote }}
  BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION: {{ printf "%s" "false" | b64enc | quote }}
  {{ else if and (not .Values.mongodb.enabled) (.Values.mongodb.externalMongo.enabled) }}
  BIGID_MONGO_HOST_EXT: {{ .Values.mongodb.externalMongo.externalIP | toString | b64enc | quote }}
  BIGID_MONGO_USER: {{ .Values.mongodb.externalMongo.auth.username | toString | b64enc | quote }}
  BIGID_MONGO_PWD: {{ .Values.mongodb.externalMongo.auth.password | toString | b64enc | quote }}
  BIGID_MONGO_PORT: {{ .Values.mongodb.externalMongo.port | toString | b64enc | quote }}
  BIGID_MONGO_SSL_DISABLE_HOSTNAME_VERIFICATION: {{ .Values.mongodb.externalMongo.mongoSSLDisableHostnameVerification | default "false" | toString | b64enc | quote }}
  BIGID_MONGO_SSL: {{ .Values.mongodb.externalMongo.mongoSSL | default "false" | toString | b64enc | quote }}
  MONGO_EXTERNAL_FULL_URL: {{ printf "%s://%s:%s@%s:%s/%s&ssl=%s&tlsAllowInvalidHostnames=%s" (toString .Values.mongodb.externalMongo.uriPrefix) (toString .Values.mongodb.externalMongo.auth.username) (toString .Values.mongodb.externalMongo.auth.password) (toString .Values.mongodb.externalMongo.externalIP) (toString .Values.mongodb.externalMongo.port) (toString .Values.mongodb.externalMongo.uri) (toString (.Values.mongodb.externalMongo.mongoSSL | default "false")) (toString (.Values.mongodb.externalMongo.mongoSSLDisableHostnameVerification | default "false")) | b64enc | quote }}
  {{- end }}
  {{- if .Values.mongodb.externalMongo.kerberos }}
  MONGO_EXTERNAL_FULL_URL: {{ printf "%s://%s@%s:%s/%s" .Values.mongodb.externalMongo.uriPrefix .Values.mongodb.externalMongo.auth.username .Values.mongodb.externalMongo.externalIP (.Values.mongodb.externalMongo.port | toString) .Values.mongodb.externalMongo.uri | b64enc | quote }}
  KRB5_CONFIG: {{ printf "/etc/kerberos/krb5.conf" | b64enc | quote }}
  KRB5_CLIENT_KTNAME: {{ printf "/etc/kerberos/mongodb.keytab" | b64enc | quote }}
  {{- end }}
  {{- if ( hasKey .Values.mongodb.externalMongo "fullUrl") }}
  {{- if .Values.mongodb.externalMongo.fullUrl }}
  MONGO_EXTERNAL_FULL_URL: {{ .Values.mongodb.externalMongo.fullUrl | toString | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
