apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-node-configuration
  namespace: {{ .Release.Namespace | quote }}
data:
  {{ if and (not .Values.mongodb.enabled) (.Values.mongodb.externalMongo.enabled) ( .Values.mongodb.externalMongo.mongoSSLCAPath) }}
  BIGID_MONGO_SSL_CA_PATH: /etc/ssl/bigid/ca.cert
  {{ if and  (.Values.mongodb.externalMongo.mongoSSLClientCertPath) ( .Values.mongodb.externalMongo.mongoSSLClientKeyPath) }}
  BIGID_MONGO_SSL_CLIENT_CERT_PATH: /etc/ssl/bigid/client.cert
  BIGID_MONGO_SSL_CLIENT_KEY_PATH: /etc/ssl/bigid/client.key
  {{- end }}
  {{- else if and (.Values.mongodb.enabled) (not .Values.mongodb.externalMongo.enabled) (.Values.mongodb.tls.enabled) }}
  BIGID_MONGO_SSL_CA_PATH: /etc/ssl/bigid/mongodb-ca-cert
  BIGID_MONGO_SSL_CLIENT_CERT_PATH: /etc/ssl/bigid/client-pem
  BIGID_MONGO_SSL_CLIENT_KEY_PATH: /etc/ssl/bigid/client-pem
  {{- end }}
