apiVersion: v1
kind: Secret
metadata:
  name: bigid-auth-secret
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  {{- if and (.Values.rabbitmq.externalRabbitmq.enabled) (not .Values.rabbitmq.enabled) }}
  rabbitmq-user: {{ .Values.rabbitmq.externalRabbitmq.auth.username | default "bigid" | b64enc | quote }}
  rabbitmq-pass: {{ .Values.rabbitmq.externalRabbitmq.auth.password | default "password" | b64enc | quote }}
  rabbitmq-host: {{ printf "http://%s:%s@bigid-mq.%s.svc.cluster.local:15672" (toString (.Values.rabbitmq.externalRabbitmq.auth.username| default "bigid")) (toString (.Values.rabbitmq.externalRabbitmq.auth.password | default "password")) (toString .Release.Namespace) | b64enc | quote }}
  {{- else }}
  rabbitmq-user: {{ .Values.rabbitmq.auth.username | default "bigid" | b64enc | quote }}
  rabbitmq-pass: {{ .Values.rabbitmq.auth.password | default "password" | b64enc | quote }}
  rabbitmq-host: {{ printf "http://%s:%s@bigid-mq.%s.svc.cluster.local:15672" (toString (.Values.rabbitmq.auth.username | default "bigid")) (toString (.Values.rabbitmq.auth.password | default "password")) (toString .Release.Namespace) | b64enc | quote }}
  {{- end }}
  {{- if and (.Values.redis.externalRedis.enabled) (not .Values.redis.enabled) }}
  redis-pass: {{ .Values.redis.externalRedis.password | default "" | b64enc | quote }}
  {{- else }}
  redis-pass: {{ .Values.redis.auth.password | default "" | b64enc | quote }}
  {{- end }}
  BIGID_ELASTICSEARCH_USER: {{ .Values.elasticsearch.security.user | b64enc | quote }}
  BIGID_ELASTICSEARCH_PWD: {{ .Values.elasticsearch.security.elasticPassword | b64enc | quote }}
