{{- if .Values.global.bigid.orchestrator2.consumer.create }}
{{- if .Values.global.bigid.orchestrator2.consumer.autoscaling.enabled }}
{{- if $.Capabilities.APIVersions.Has "keda.sh/v1alpha1" }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bigid-orch2-consumer
  labels:
    deploymentName: bigid-orch2-consumer
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
  namespace: {{ .Release.Namespace | quote }}
spec:
  advanced:
    horizontalPodAutoscalerConfig:
      name: bigid-orch2-consumer
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.global.bigid.orchestrator2.autoscaling.scaleDownPolicy.stabilizationWindowSeconds }}
          policies:
          - type: Percent
            value: {{ .Values.global.bigid.orchestrator2.autoscaling.scaleDownPolicy.value }}
            periodSeconds: {{ .Values.global.bigid.orchestrator2.autoscaling.scaleDownPolicy.periodSeconds }}
  maxReplicaCount: {{ .Values.global.bigid.orchestrator2.consumer.autoscaling.maxReplicas }}
  minReplicaCount: {{ .Values.global.bigid.orchestrator2.consumer.autoscaling.minReplicas }}
  pollingInterval: 30
  cooldownPeriod:  {{ .Values.global.bigid.orchestrator2.autoscaling.scaleDownPolicy.stabilizationWindowSeconds }}
  scaleTargetRef:
    name: bigid-orch2-consumer
  triggers:
    - type: rabbitmq
      metadata:
        mode: QueueLength # QueueLength or MessageRate
        value: {{ .Values.global.bigid.orchestrator2.consumer.autoscaling.averageValue | quote }} # message backlog or publish/sec. target per instance
        activationValue: "1" # Optional. Activation threshold
        queueName: ^(enrichment.findings.*|classification.findings.*|pii.findings.*|orch.enrichDsarProfileFields.queue|catalog.object.scan.completed.*|catalog.object.diff.dsInsight.queue|correlator.finishCorrelation.durable.queue|correlator.aggregateClassification.queue|orch.object.attributes.queue|updateConfLvlSarFields\*)$
        useRegex: "true"
        vhostName: /
        timeout: "120"
      authenticationRef:
        name: bigid-orch2-consumer-trigger-auth
{{- end }}
{{- end }}
{{- end }}
