apiVersion: v1
kind: ConfigMap
metadata:
  name: mq-config
data:
  enabled_plugins: |
      [rabbitmq_management].
  definitions.json: |-
    {
      "users": [
        {
          "name": "bigid",
          "password_hash": "orsOILvMtSo8I7jaqjKB72rY8O/u5SGz8qKZnBLXKuUmqofd",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "administrator"
        },
        {
          "name": "monitor",
          "password_hash": "f1lgJopeLUGkVXZj2icsn7yipXsqKshLZ7t5rgKHHA/CXeIZ",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": "monitoring"
        }
      ],
      "permissions": [
        {
          "user": "bigid",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        },
        {
          "user": "monitor",
          "vhost": "/",
          "configure": "NONE",
          "write": "NONE",
          "read": "NONE"
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ]
    }
  rabbitmq.config: |-
    [

        {rabbit, [
             {ssl_listeners, [5671]},
             {consumer_timeout, 432000000},
             {total_memory_available_override_value, "{{ .Values.global.bigid.rabbitmq.resources.limits.memory }}B" },
             {ssl_options, [{cacertfile,"/etc/rabbitmq/certfiles/cacert.pem"},
                            {certfile,"/etc/rabbitmq/certfiles/cert.pem"},
                            {keyfile,"/etc/rabbitmq/certfiles/key.pem"},
                            {verify,verify_peer},
                            {fail_if_no_peer_cert,false}]},
              {load_definitions, "/etc/rabbitmq/config/definitions.json"}
           ]},
           {rabbitmq_management, [{listener, [{port, 15671},
                                  {ssl, true},
                                  {ssl_opts, [{cacertfile, "/etc/rabbitmq/certfiles/cacert.pem"},
                                              {certfile, "/etc/rabbitmq/certfiles/cert.pem"},
                                              {keyfile, "/etc/rabbitmq/certfiles/key.pem"},
                                              {verify, verify_none},
                                              {versions, ['tlsv1.2']},
                                              {fail_if_no_peer_cert,false}]}
                                    ]}
           ]}
     ].
