global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param podAnnotations Annotations for BigiD pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  podAnnotations: {}
  bigid:
    ## @param global.bigid.containerSecurityContext Security Context for BigID containers
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
    ## @param global.bigid.podSecurityContext Security Context for BigID pods
    podSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsGroup: 1001
      # capabilities:
      #   drop:
      #   - ALL
      #   - NET_RAW
      # # readOnlyRootFilesystem: true
      # allowPrivilegeEscalation: false
      # runAsNonRoot: true
    correlator:
      replicaCount: 1
      serviceAccount:
        create: true
        annotations: {}
      image:
        repository: "bigid-corr-new"
      initContainer:
        image:
          repository: ""
      nodeSelector: {}
      port: 7082
      cacheSize: 10
      ignite:
        enabled: false
        clusterName: ignite
        namespace: gridgain
        # Options: PARTITIONED / REPLICATED
        cacheMode: PARTITIONED
        backups: 3
      numbersLengthThreshold: 9
      podAnnotations: {}
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      extraEnvVars: []
      consumerThreadNumber: 2
      maxConnectionsPerRoute: 5
      maxTotalConnections: 10
      terminationGracePeriodSeconds: 300
      rabbitmqConsumersShutdownTimeoutMsec: 295000
      shouldDropRedeliveredMessages: false
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 3
        averageValue: 250
        scaleDownPolicy:
          stabilizationWindowSeconds: 900
          periodSeconds: 300
          value: 10
      JavaOpts: "-Dspring.lifecycle.timeout-per-shutdown-phase=5m"
      heapSizePercent: 85
