{{- if .Values.global.bigid.actionCenter.create -}}
apiVersion: v1
kind: Service
metadata:
  name: bigid-action-center
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-action-center
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ports:
    - port: {{ .Values.global.bigid.actionCenter.port }}
      targetPort: {{ .Values.global.bigid.actionCenter.port }}
      name: http
  selector:
    app: bigid-action-center
{{- end }}
