{{- if .Values.global.bigid.confluent.create -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigid-confluent
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-confluent
    {{- with .Values.global.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{ include "global.skipCheckovAnnotations" . | nindent 4 }}
    {{- with .Values.global.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.global.bigid.confluent.replicaCount }}
  selector:
    matchLabels:
      app: bigid-confluent
      {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 6 }}
      {{- end }}
  {{- if .Values.global.bigid.confluent.updateStrategy }}
  strategy: {{- toYaml .Values.global.bigid.confluent.updateStrategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.global.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: bigid-confluent
        {{- with .Values.global.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccount: bigid-confluent
      automountServiceAccountToken: false
      initContainers:
      - name: init-config-service
        image: {{ template "initContainer.image" . }}
        imagePullPolicy: {{ .Values.global.image.pullPolicy }}
        command: ['sh', '-c', "until wget -q --spider http://bigid-config-service:{{ .Values.global.bigid.configService.port }}/actuator/health; do echo waiting for bigid-config-service; sleep 3; done"]
        resources:
          {{- toYaml .Values.global.initContainers.resources | nindent 10 }}
        {{- if .Values.global.initContainers.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.global.initContainers.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
      containers:
      - image: landoop/fast-data-dev:2.0.1
        imagePullPolicy: IfNotPresent
        name: bigid-confluent
        env:
        - name: ADV_HOST
          value: "bigid-confluent"
        - name: RUNTESTS # Disable Running tests so the cluster starts faster
          value: "0"
        - name: FORWARDLOGS # Disable running 5 file source connectors that bring application logs into Kafka topics
          value: "0"
        - name: SAMPLEDATA  # Do not create sea_vessel_position_reports, nyc_yellow_taxi_trip_data, reddit_posts topics with sample Avro records.
          value: "0"
        # - name: ENABLE_SSL  # SSL on
        #   value: 1
        resources:
          {{- toYaml .Values.global.bigid.confluent.resources | nindent 10 }}
        {{- if .Values.global.bigid.confluent.containerSecurityContext.enabled }}
        securityContext: {{- omit .Values.global.bigid.confluent.containerSecurityContext "enabled" | toYaml | nindent 10 }}
        {{- end }}
      imagePullSecrets:
      {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- if .Values.global.bigid.confluent.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.global.bigid.confluent.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
