{{- if .Values.global.bigid.confluent.create -}}
{{- if .Values.global.bigid.confluent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bigid-confluent
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: bigid-confluent
  {{- with .Values.global.bigid.confluent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
automountServiceAccountToken: false
{{- end }}
