{{- if and (.Values.global.bigid.scanner.remote.enabled ) (.Values.global.imageCredentials.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end -}}
