enabled: false

global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## @param podAnnotations Annotations for BigiD pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  imagePullSecret: []
  bigid:
    generateToken:
      enabled: false

    ## @param global.bigid.containerSecurityContext Security Context for BigID containers
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
    ## @param global.bigid.podSecurityContext Security Context for BigID pods
    podSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsGroup: 1001

mongodb:
  ssl: false
  byExternalFullUrl: true
  mongoUri: "bigid-retention?authSource=admin&replicaSet=bigid-replica-set"
  ## Fill in the complete MongoDB connection string in the standard format to establish a full connection.
  ## Example: "mongodb://<username>:<password>@<host>:<port>/<database>?<options>"
  mongoFullUrl: ""
  # SSL properties with SCRAM-SHA-1 or SCRAM-SHA-256 mechanism
  # SSL properties with X509 mechanism, where "mongodbssl" is MongoDB started in SSL mode with clusterAuthMode=x509
  #externalFullUrl: mongodb://bigid-mongodb-headless:27017/data-retention?authSource=$external&replicaSet=bigid-replica-set&ssl=true&tlsAllowInvalidHostnames=true&authMechanism=MONGODB-X509

image:
  registry: 656782941097.dkr.ecr.us-east-1.amazonaws.com
  tag: "3.4.0.192"

gateway:
  replicaCount: 1
  profile: prod
  serviceUserJWT: ""
  dsarTimeout: "86400000"
  # Jvm options without SSL properties
  jvmOpts: -server -Xmx1g -Dlogging.file.path=/usr/local/dataretention/logs -Dlogging.file.name=web-gateway.log -Dlogging.file.nameDebug=web-gateway-debug.log -Dlogging.file.nameAccess=web-gateway-access.log
  # Jvm options with SSL properties
  #jvmOpts: -server -Xmx1g -Dlogging.file.path=/usr/local/dataretention/logs -Dlogging.file.name=web-gateway.log -Dlogging.file.nameDebug=web-gateway-debug.log -Dlogging.file.nameAccess=web-gateway-access.log -Djavax.net.ssl.keyStore=/etc/ssl/bigid/client.jks  -Djavax.net.ssl.keyStorePassword=password1 -Djavax.net.ssl.trustStore=/etc/ssl/bigid/truststore.jks -Djavax.net.ssl.trustStorePassword=password1

  image:
    repository: bigid/data-retention/web-gateway

  service:
    port: 8080
    targetPort: 8080
    portName: http

  resources:
    requests:
      memory: 2Gi
      cpu: 2
    limits:
      memory: 8Gi
      cpu: 4

ui:
  replicaCount: 1
  image:
    repository: bigid/data-retention/web-ui

  service:
    port: 8081
    targetPort: 8081

  resources:
    requests:
      memory: 1Gi
      cpu: 1
    limits:
      memory: 2Gi
      cpu: 1
