{{- if .Values.global.bigid.useSaas.enabled }}
{{- if ( hasKey .Values.global.bigid "generateToken") }}
{{- if .Values.global.bigid.generateToken.enabled | default false }}
apiVersion: batch/v1
kind: Job
metadata:
  name: post-install
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "1"
    helm.sh/hook-delete-policy: before-hook-creation
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      terminationGracePeriodSeconds: 0
      containers:
      - name: post-install
        image: 656782941097.dkr.ecr.us-east-1.amazonaws.com/bigid/alpine:3.14
        imagePullPolicy: IfNotPresent
        command: [ "/scripts/entrypoint.sh" ]
        env:
        - name: BIGID_WEB
          value: "http://bigid-web:3000"
        - name: BIGID_CORE_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: bigid-jwt-token
              key: token
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
      volumes:
      - name: scripts-volume
        configMap:
          name: post-install-configmap
          defaultMode: 0744
      {{- with .Values.mongodb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
