{{- if .Values.global.bigid.useSaas.enabled }}
{{- if ( hasKey .Values.global.bigid "generateToken") }}
{{- if .Values.global.bigid.generateToken.enabled | default false }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: post-install-configmap
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  entrypoint.sh: |
   #!/bin/sh

   set -e

   echo "Fetching system token ..."

   TOKEN=$(curl -s -H "Authorization: ${BIGID_CORE_REFRESH_TOKEN}" -H "Content-Type: application/json" -X GET ${BIGID_WEB}/api/v1/refresh-access-token | jq -r '.systemToken')

   if [ -z "${TOKEN}" ]; then
      echo "Could not fetch system token ..."
      exit 0;
   else
      echo "Enabling AWS secret less authentication ..."
      curl -s -H "Authorization: ${TOKEN}" -H "Content-Type: application/json" -X POST ${BIGID_WEB}/api/v1/saas/external-id
   fi
{{- end }}
{{- end }}
{{- end }}
