{{- if hasKey .Values.mongodb "archive" }}
{{- if .Values.mongodb.archive.backup.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.mongodb.archive.serviceAccount }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - pods
  verbs:
  - list
  - get
  - delete
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  - statefulsets/scale
  - deployments/scale
  verbs:
  - list
  - get
  - patch
{{- end }}
{{- end }}
