{{- if hasKey .Values.mongodb "archive" }}
{{- if .Values.mongodb.archive.backup.ses.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ses-email-notifications-secrets
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
  SES_RECIPIENT: {{ .Values.mongodb.archive.backup.ses.recipient | b64enc }}
  SES_AWS_ACCESS_KEY_ID: {{ .Values.mongodb.archive.backup.ses.username | b64enc }}
  SES_AWS_SECRET_ACCESS_KEY: {{ .Values.mongodb.archive.backup.ses.password | b64enc }}
{{- end }}
{{- end }}
