{{- if .Values.global.bigid.tenantService.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tenant-service.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tenant-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.global.bigid.tenantService.service.type }}
  ports:
    - port: {{ .Values.global.bigid.tenantService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tenant-service.selectorLabels" . | nindent 4 }}
{{- end }}
