global:
  # Default node selector for bigid services (except of rmq/mongo/redis)
  nodeSelector: {}
  ## @param affinity Affinity for pod assignment. Evaluated as a template
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
  ## @param master.tolerations Tolerations for master-elegible pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: []
  ## Default podAnnotations for bigid pods (except of rmq/mongo/redis)
  ## @param podAnnotations Annotations for BigiD pods (except of rmq/mongo/redis)
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  podAnnotations: {}
  bigid:
    # BigID Scheduler settings
    bigidScheduler:
      # Set to true to enable the BigID Scheduler feature
      enabled: true
      # Set to true to enable metrics for BigID Scheduler
      metricsEnabled: true
      # Set to true to enable logging of job triggers for BigID Scheduler
      logJobTriggeredEnabled: true
      # Cron expression for collecting metrics on the count of jobs executed in orch2
      jobsCountMetricsCronExp: "*/5 * * * *"
      # Cron expression for collecting metrics on the count of job triggers in orch2
      jobsTriggeredCountMetricsCronExp: "*/5 * * * *"
      # Time-to-live (TTL) for the job modification lock in milliseconds in orch2
      jobModifylockTtlMs: 5000

    ## @param global.bigid.containerSecurityContext Security Context for BigID containers
    containerSecurityContext:
      enabled: true
      runAsUser: 1001
      runAsGroup: 1001
    ## @param global.bigid.podSecurityContext Security Context for BigID pods
    podSecurityContext:
      enabled: false
      runAsUser: 1001
      runAsGroup: 1001
    saasEnv: "staging"
    aci:
      replicaCount: 1
      image:
        repository: "bigid-aci"
      podAnnotations: {}
      autoscaling:
        enabled: false
        minReplicas: 1
        maxReplicas: 8
        targetCPUUtilizationPercentage: ""
        averageValue: 250
        scaleDownPolicy:
          periodSeconds: 300
          stabilizationWindowSeconds: 900
          value: 10
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      usePrefetchSupportedConsumers: true
      prefetchCountDefault: 100
      prefetchCountACIExecution: 100
      prefetchCountDashboardFetchDS: 1
      prefetchCountDashboardDeleteDS: 1
      prefetchCountLabeling: 100
      prefetchCountLabelsUpdate: 1
      prefetchCountSensitivityClassificationBootstrap: 10
      prefetchCountSensitivityClassificationDiffEvents: 10
      prefetchCountSensitivityClassificationStructured: 10
      prefetchCountSensitivityClassificationUnstructured: 100
      prefetchCountRouteCatalogDiffsToSCQueue: 300
      prefetchCountInternalTask: 100
      DefaultMaxAckTimeSec: 1800
      DefaultMaxAckTimeDashboardFetchDSSec: 1800
      DefaultMaxAckTimDashboardDeleteDSSec: 1800
      DefaultMaxAckTimeLabelingSec: 1800
      aciDashboardInProgressTimeoutMs: 300000
      extraEnvVars: []
      port: 4001
      nodeOptions: ""
      nodeMaxOldSpaceSizePercent: 85
      resources:
        requests:
          memory: "1Gi"
          cpu: "1"
        limits:
          memory: "6Gi"
          cpu: "1"
      aciDashboardGenerationEnabled: true
      coaDirectAccessPoliciesEnabled: false
      serviceAccount:
        create: true
        annotations: {}
