{{- if .Values.global.bigid.clustering.create }}
{{- if or .Values.global.bigid.clustering.worker.autoscaling.enabled .Values.global.bigid.clustering.scheduler.autoscaling.enabled .Values.global.bigid.clustering.hotspots.autoscaling.enabled }}
{{- if $.Capabilities.APIVersions.Has "keda.sh/v1alpha1" }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: bigid-ml-trigger-auth
  namespace: {{ .Release.Namespace | quote }}
spec:
  secretTargetRef:
    - parameter: host
      name: bigid-auth-secret
      key: rabbitmq-host
{{- end }}
{{- end }}
{{- end }}

